---
title: "roster_specific"
output: pdf_document
date: "2024-07-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(readr)
library(tidyverse)
library(dplyr)
library(stringr)
library(lubridate)
```


```{r loadingdata}
# using data from 2017-2024

newdata <- read.csv("gym_data_22_24.csv")
data_2017_2021 <- read_csv("App-1/data/data_2017_2021.csv")
rawdata <- rbind(newdata, data_2017_2021)
```


```{r cleaning function}

data_cleaning <- function(data) {
  #DO NOT CHANGE ORDER
  
  data$Apparatus[data$Apparatus == "VT2"] <- "VT"
  data$Apparatus[data$Apparatus == "VT1"] <- "VT"
  data$Apparatus[data$Apparatus == "UE"] <- "UB"
  
  data$Penalty[is.na(data$Penalty)] <- 0
  
  #Girls filtering for middle name
  data$FirstName[data$FirstName == "Joscelyn Michelle"] <- "Joscelyn"
  data$FirstName[data$FirstName == "Nola Rhianne"] <- "Nola"
  
  #Guys filtering for middle name
  data$FirstName[data$FirstName == "Taylor Troy"] <- "Taylor"
  data$FirstName[data$FirstName == "Joshua Andrew"] <- "Joshua"
  data$FirstName[data$FirstName == "Yul Kyung Tae"] <- "Yul"
  data$FirstName[data$FirstName == "Curran Michael"] <- "Curran"
  data$FirstName[data$FirstName == "Frederick Nathaniel"] <- "Frederick"
  data$FirstName[data$FirstName == "Ian Hunter"] <- "Ian"
  data$FirstName[data$FirstName == "Shane Michael"] <- "Shane"
  data$FirstName[data$FirstName == "Khoi Alexander"] <- "Khoi"
  
  data$FirstName[data$FirstName == "Yunus Emre"] <- "Yunus"
  
  data$FirstName[data$FirstName == "Yuan-Hsi"] <- "Yuan Hsi"
  
  data$FirstName[data$FirstName == "Yu-Jan"] <- "Yu Jan"
  
  data$LastName[data$LastName == "VILLAVERDE MEDEROS"] <- "VILLAVERDE"
  
  data$LastName[data$LastName == "VALENZUELA ASTUDILLO"] <- "VALENZUELA"
  
  data$FirstName[data$FirstName == "Yiseth Eliana"] <- "Yiseth"
  data$FirstName[data$FirstName == "Yi-Chen"] <- "Yi Chen"
  data$FirstName[data$FirstName == "Yi-Chun"] <- "Yi Chun"
  
  data$FirstName[data$FirstName == "Yefferson Gregorio"] <- "Yefferson"
  data$LastName[data$LastName == "ANTON YEGUEZ"] <- "ANTON"
  
  data$LastName[data$LastName == "ANTON YEGUEZ"] <- "ANTON"
  
  data$FirstName[data$FirstName == "Wout Johan Alexander"] <- "Wout"
  
  data$FirstName[data$FirstName == "Wilfry Manuel"] <- "Wilfry"
  
  data$FirstName[data$FirstName == "Wei-Sheng"] <- "Wei Sheng"
  
  data$FirstName[(data$Competition == "BIRMINGHAM 2022 Commonwealth Games") &
                             (is.na(data$LastName))] <- "Kate"
  
  data$LastName[(data$Competition == "BIRMINGHAM 2022 Commonwealth Games") &
                            (is.na(data$LastName))] <- "MCDONALD"
  
  data$FirstName[data$LastName == "SOUZA BITENCOU"] <- "Lucas"
  data$LastName[data$LastName == "SOUZA BITENCOU"] <- "BITENCOURT"
  
  data$LastName[data$LastName == "DE JESUS DOS SANTOS"] <- "JESUS SANTOS"
  
  data$FirstName[data$LastName == "JESUS SANT"] <- "Melanie"
  data$LastName[data$LastName == "JESUS SANT"] <- "JESUS SANTOS"
  
  data$LastName[data$LastName == "ELPITIYA BADALGE DONA"] <- "GEHANI"
  data$FirstName[data$FirstName == "Milka Gehani"] <- "Milka"
  
  data$FirstName[data$LastName == "ELPITIYA BADALG D"] <- "Milka"
  
  data$LastName[data$LastName == "ELPITIYA BADALG D"] <- "GEHANI"
  
  data$FirstName[(data$Competition == "2022 51st FIG Artistic Gymnastics World Championship") &
                             (is.na(data$LastName))] <- "Kate"
  
  data$LastName[(data$Competition == "2022 51st FIG Artistic Gymnastics World Championship") &
                            (is.na(data$LastName))] <- "MCDONALD"
  
  data$FirstName[(data$Competition == "2023 Varna World Challenge Cup") &
                             (is.na(data$LastName))] <- "Daria"
  
  data$LastName[(data$Competition == "2023 Varna World Challenge Cup") &
                            (is.na(data$LastName))] <- "HARTMANN"
  
  data$FirstName[data$LastName == "ABIYURAFI"] <- "Abiyu"
  data$LastName[data$LastName == "ABIYURAFI"] <- "Rafi"
  
  data$FirstName[data$LastName == "Frederick Nathaniel"] <- "Frederick"
  data$FirstName[data$FirstName == "Fred"] <- "FREDERICK"
  data$FirstName[data$FirstName == "Viktoriia"] <- "Viktoria"
  data$LastName[data$LastName == "D AMATO"] <- "D'AMATO"
  data$LastName[data$LastName == "VERNAIEV"] <- "VERNIAIEV"
  
  data <- data %>% mutate(LastName = str_to_title(LastName))
  
  data$Apparatus[data$Apparatus == "VT2"] <- "VT"
  data$Apparatus[data$Apparatus == "VT1"] <- "VT"
  
  # data cleaning
  extract_second_date <- function(date_string) {
  parts <- str_extract_all(date_string, "\\d{1,2}\\s[A-Za-z]+\\s\\d{4}")[[1]]
  if (length(parts) == 2) {
    # If there are two dates, return the second one
    return(parts[2])
  } else if (length(parts) == 1) {
    # If there is only one date, return it
    return(parts[1])
  } else {
    return(NA)
  }
}

# Step 2: Apply the function to the Date column and convert to Date objects
data <- data %>%
  mutate(
    SecondDateStr = sapply(Date, extract_second_date),
    SecondDate = dmy(SecondDateStr)
  )

# Define the end date
end_date <- dmy("27-07-2024")

# Calculate the number of days from the SecondDate to the end date
data <- data %>%
  mutate(
    DaysUntil2024 = as.integer(end_date - SecondDate)
  )
  
  
  
}

```

```{r cleaning}
cleaned_data <- data_cleaning(rawdata)
```



### Rosters

```{r mens international}
CAN_m <- c("Zachary Clay","Rene Cournoyer", "Felix Dolci", "William Emard", "Sam Zakutney")
CHN_m <- c("Yang Liu", "Weide Su", "Ruoteng Xiao", "Boheng Zhang", "Jingyuan Zou")
GER_m <- c("Pascal Brendel", "Lukas Dauser", "Nils Dunkel", "Timo Eder", "Andreas Toba")
GBR_m <- c("Joe Fraser", "Harry Hepworth", "Jake Jarman", "Luke Whitehouse", "Max Whitlock")
ITA_m <- c("Yumin Abbadini", "Nicola Bartolini", "Lorenzo Minh Casali", "Mario Macchiati", "Carlo Macchini")
JPN_m <- c("Daiki Hashimoto", "Kazuma Kaya", "Shinnosuke Oka", "Takaaki Sugino", "Wataru Tanigawa")
NED_m <- c("Loran De Munck", "Martijn De Veer", "Jermain Gruenberg", "Frank Rijken", "Casimir Schmidt")
ESP_m <- c("Nestor Abad", "Thierno Diallo", "Nicolau Mir", "Joel Plata", "Rayderley Zapata")
SUI_m <- c("Luca Giubellini","Matteo Giubellini", "Florian Langenegger", "Noe Seifert", "Taha Serhani")
TUR_m <- c("Ferhat Arican", "Adem Asil", "Ibrahim Colak", "Emre Dodanli", "Ahmet Onder")
UKR_m <- c("Nazar Chepurnyi", "Illia Kovtun", "Igor Radivilov", "Radomyr Stelmakh", "Oleg Verniaiev")
USA_m <- c("Asher Hong", "Paul Juda", "Brody Malone", "Stephen Nedoroscik", "Frederick Richard")
individual_m <- c("Jesse Moore", "Artur Davtyan", "Vahagn Davtyan", "Glen Cuyle", "Noah Kuavita", "Luka Van Den Keybus", "Arthur Mariano", "Diogo Soares", "Kevin Penev", "Chia-Hung Tang","Angel Barajas", "Aurel Benovic", "Tin Srbic", "Marios Georgiou","Audrys Nin Reyes", "Omar Mohamed", "Samir Ait Said", "Eleftherios Petrounias", "Wai Hung Shek ","Krisztofer Meszaros", "Mahdi Olfati", "Rhys Mcclenaghan", "Artem Dolgopyat", "Ahmad Abu Al Soud", "Milad Karimi", "Nariman Kurbanov", "Robert Tvorogal", "Carlos Yulo", "Andrei Muntean", "Woong Hur", "Junho Lee", "Sunghyun Ryu", "Lais Najjar","Rasuljon Abdurakhimov", "Abdulla Azimov","Khabibullo Ergashev")
```

```{r womens rosters}
AUS_w <- c("Kate Mcdonald", "Emma Nedov", "Ruby Pass", "Breanna Scott", "Emily Whitehead")
BRA_w <- c("Rebeca Andrade", "Jade Barbosa", "Lorrane Oliveira", "Flavia Saraiva","Julia Soares")
CAN_w <- c("Ellie Black", "Cassie Lee", "Shallon Olsen", "Ava Stewart", "Aurelie Tran")
CHN_w <- c("Huan Luo", "Yushan Ou", "Qiyuan Qiu", "Yihan Zhang", "Yaqin Zhou")
FRA_w <- c("Marine Boyer", "Coline Devillard", "Melanie Jesus Santos", "Morgane Osyssek-Reimer", "Ming Van Eijken")
GBR_w <- c("Rebecca Downie", "Ruby Evans", "Georgia Mae Fenton", "Alice Kinsella", "Abigail Martin")
ITA_w <- c("Angela Andreoli", "Alice D'amato", "Manila Esposito", "Elisa Iorio", "Giorgia Villa")
JPN_w <- c("Rina Kishi", "Haruka Nakamura", "Mana Okamura", "Kohane Ushioku") ## 5th athelte??? 
NED_w <- c("Sanna Veerman", "Naomi Visser", "Tisha Volleman", "Lieke Wevers", "Sanne Wevers")
ROU_w <- c("Ana Barbosu", "Lilia Cosman", "Amalia Ghigoarta", "Andreea Preda", "Sabrina Maneca-Voinea")
KOR_w <- c("Dohyun Eom", "Dayeong Lee", "Yunseo Lee", "Solyi Shin", "Seojeong Yeo")
USA_w <- c("Simone Biles", "Jade Carey", "Jordan Chiles", "Sunisa Lee", "Hezly Rivera")

individuals_w <- c("Kaylia Nemour", "Charlize Moerz", "Maellyse Brassart", "Nina Derwael", "Valentina Georgieva", "Hua-Tien Ting", "Luisa Blanco", "Sona Artamonova", "Jana Mahmoud", "Helen Kevric", "Pauline Schaefer Betz", "Sarah Voss", "Lynnzee Brown", "Csenge Maria Bacskay", "Bettina Lili Czifra", "Zsofia Kovacs", "Rifda Irfanaluthfi","Lihie Raz", "Natalia Escalera", "Alexa Moreno", "Ahtziri Sandoval", "Georgia Rose Brown", "Changok An", "Hillary Heron", "Aleah Finnegan", "Emma Malabuyo", "Levi Ruivivar", "Filipa Martins", "Lucija Hribar", "Caitlin Rooskrantz", "Laura Casabuena", "Ana Perez", "Alba Petisco", "Lena Bickel", "Anna Lashchevska")
```

```{r}
# Combine all rosters into one list
all_athletes <- c(
  CAN_m, CHN_m, GER_m, GBR_m, ITA_m, JPN_m, NED_m, ESP_m, SUI_m, TUR_m, UKR_m, USA_m, individual_m,
  AUS_w, BRA_w, CAN_w, CHN_w, FRA_w, GBR_w, ITA_w, JPN_w, NED_w, ROU_w, KOR_w, USA_w, individuals_w
)

```


```{r}
nfix <- function(dataset) {
    dataset <- as.data.frame(dataset)
    # dataset$LastName <- sapply(strsplit(tolower(dataset$LastName), " "), function(x) {
    #   paste(sapply(x, function(y) {
    #     paste0(toupper(substring(y, 1, 1)), substring(y, 2))
    #   }), collapse = " ")
    # })
    
    # Create FullName in f dataset
    dataset$FullName <- paste(dataset$FirstName, dataset$LastName, sep=" ")
    
    #fnd <- select(dataset,18,3:17)
    return (dataset)
}

fuln <- nfix(cleaned_data)
olympic_athletes <- fuln %>% 
  filter(FullName %in% all_athletes)
```

```{r}
write.csv(olympic_athletes, "App-1/data/rostersims/cleaned_oly.csv",row.names = FALSE)
```



### Simulations

```{r sampling_dist}

create_sampling_dist <- function(data){
  final_rows_full <- data[grep("final|Final", data$Round), ]
  less_than_180_rows <- data[data$DaysUntil2024 < 180, ]
  between_180_540_rows <- data[data$DaysUntil2024 >= 180 &
                                 data$DaysUntil2024 <= 540, ]
  
  sampling_data <- rbind(
    data,
    final_rows_full,
    less_than_180_rows,
    less_than_180_rows,
    between_180_540_rows
  )
  return (sampling_data)


}
sampling_data <- create_sampling_dist(olympic_athletes)
sampling_data <- sampling_data %>% 
  filter(!is.na(Score))

```

```{r simulate func}
simulate_gymnastics_event <- function(event_name, gender, nsimulation) {
  set.seed(123)

  # Select the appropriate dataframe based on gender
  if (gender == "f") {
    gymnast_data <- sampling_data %>% filter(Gender == "w")
  } else if (gender == "m") {
    gymnast_data <- sampling_data %>% filter(Gender == "m")
  } else {
    stop("Invalid gender. Use 'f' for female or 'm' for male.")
  }

  # Identify unique gymnasts
  unique_gymnasts <- unique(gymnast_data[, c("FirstName", "LastName", "Country")])

  # Create a new dataframe to store sampled scores
  n_iterations_data <- data.frame(
    FirstName = character(),
    LastName = character(),
    Country = character()
  )

  for (n in 1:nsimulation) {
    sampled_scores_data <- data.frame(
      FirstName = character(),
      LastName = character(),
      Country = character(),
      stringsAsFactors = FALSE
    )

    for (i in 1:nrow(unique_gymnasts)) {
      # Extract the current gymnast's information
      current_gymnast <- unique_gymnasts[i, ]

      # Subset the data for the current gymnast
      subset_data <- gymnast_data[
        gymnast_data$FirstName == current_gymnast$FirstName &
        gymnast_data$LastName == current_gymnast$LastName &
        gymnast_data$Apparatus == event_name,
      ]

      # Check if the gymnast has at least 5 rows of data
      if (nrow(subset_data) < 5) {
        next  # Skip to the next gymnast
      }

      if (nrow(subset_data) == 0) {
        # If the subset is empty, set the sampled value to 0
        sampled_score <- 0
      } else {
        # Calculate mean and standard deviation
        mean_score <- mean(subset_data$Score)
        sd_score <- sd(subset_data$Score)
        max_cutoff <- max(subset_data$Score) + 0.3

        # Initialize sampled_score
        sampled_score <- NA

        # Sample from the t-distribution until the score is less than or equal to max_cutoff
        while (is.na(sampled_score) || sampled_score > max_cutoff) {
          df <- max(nrow(subset_data) - 1, 1)  # to avoid df being zero
          sampled_score <- mean_score + rt(1, df) * sd_score
        }
      }

      # Create a data frame for the current gymnast's sampled scores
      current_data <- data.frame(
        FirstName = current_gymnast$FirstName,
        LastName = current_gymnast$LastName,
        Country = current_gymnast$Country,
        Score = sampled_score,
        stringsAsFactors = FALSE
      )

      # Append the current data to the overall sampled_scores_data dataframe
      sampled_scores_data <- rbind(sampled_scores_data, current_data)
    }

    # Combine the scores into n_iterations_data
    if (n == 1) {
    n_iterations_data <- sampled_scores_data
    } else {
    n_iterations_data <- cbind(n_iterations_data, sampled_scores_data$Score)
    colnames(n_iterations_data)[ncol(n_iterations_data)] <- paste("Score_", n, sep = "")
  }

  }
    # add an average scores across sims for each athlete
    columns_to_average <- n_iterations_data[, -(1:3)]

    # Calculate the row-wise mean for the selected columns
    n_iterations_data$AverageScore <- rowMeans(columns_to_average, na.rm = TRUE)
    #final_average_df <- n_iterations_data[, c(1, 2, ncol(n_iterations_data))]
    #final_average_df = final_average_df[order(-final_average_df$AverageScore), ]

  return(n_iterations_data)
}
```


```{r womens sims}
# List of women's events
women_events <- c("BB", "UB", "FX", "VT")

# Number of simulations
nsimulation <- 400

# Loop over women's events
for (event_name in women_events) {
  # Generate dataframe name
  dataframe_name <- paste0(event_name, "_womens_sims")

  # Run the function for the specific event and save the results
  tempsims <- assign(dataframe_name, simulate_gymnastics_event(event_name, "f", nsimulation))
  path <- paste0("App-1/data/rostersims/",dataframe_name,".csv")
  write.csv(tempsims, path, row.names = FALSE)
}

```


```{r all-around-sims womens}
BB_sims <- read_csv("App-1/data/rostersims/BB_womens_sims.csv")
FX_sims <- read_csv("App-1/data/rostersims/FX_womens_sims.csv")
UB_sims <- read_csv("App-1/data/rostersims/UB_womens_sims.csv")
VT_sims <- read_csv("App-1/data/rostersims/VT_womens_sims.csv")

# Define a function to replace NA with 0 and drop the average score column
prepare_df <- function(df) {
  df %>% 
    mutate(across(starts_with("Score"), ~ replace_na(., 0)))
}

BB_sims_prepared <- prepare_df(BB_sims)
FX_sims_prepared <- prepare_df(FX_sims)
UB_sims_prepared <- prepare_df(UB_sims)
VT_sims_prepared <- prepare_df(VT_sims)

# Use left joins to combine the dataframes
combined_AA_df <- BB_sims_prepared %>%
  left_join(FX_sims_prepared, by = c("FirstName", "LastName", "Country")) %>%
  left_join(UB_sims_prepared, by = c("FirstName", "LastName", "Country")) %>%
  left_join(VT_sims_prepared, by = c("FirstName", "LastName", "Country"))
```



```{r sum-across-events-women}
# Assuming your dataframe is called 'your_dataframe'
# Assuming you have 4004 columns and 38 rows

# Create a vector of column indices to sum
original_data <- combined_AA_df[, -(1:3)]
names <- combined_AA_df[, (1:3)]


# Sum every 1000th column and store the result in the condensed dataframe
condensed_data <- data.frame(matrix(NA, nrow = nrow(names), ncol = 401))

# Loop through each group of 1000 columns
for (i in 1:401) {
  # Identify the columns in the current group
  current_group_columns <- c(i, i + 400,i+800,i+1200)
  #print(current_group_columns)
  # Sum the values across the columns in the current group
  condensed_data[, i] <- rowSums(original_data[, current_group_columns], na.rm = TRUE)
}

# Rename the columns of the condensed dataframe
colnames(condensed_data) <- paste0("Condensed_Column_", 1:ncol(condensed_data))

# Print or use the condensed dataframe as needed
combinedfinalAA <- cbind(names,condensed_data)

columns_to_average_women <- combinedfinalAA[, -(1:3)]

# Calculate the row-wise mean for the selected columns
combinedfinalAA$AverageScore <- rowMeans(columns_to_average_women, na.rm = TRUE)

write.csv(combinedfinalAA, "App-1/data/rostersims/AA_womens_sims.csv", row.names = FALSE)
```


```{r mens sims}
# List of men's events
men_events <- c("PB", "HB", "PH", "FX", "SR", "VT")

# Number of simulations
nsimulation <- 400

# Loop over men's events
for (event_name in men_events) {
  # Generate dataframe name
  dataframe_name <- paste0(event_name, "_mens_sims")

  # Run the function for the specific event and save the results
  tempsims <- assign(dataframe_name, simulate_gymnastics_event(event_name, "m", nsimulation))
  path <- paste0("App-1/data/rostersims/",dataframe_name,".csv")
  write.csv(tempsims, path, row.names = FALSE)
}

```

```{r all-around-sims men}
HB_sims_m <- read_csv("App-1/data/rostersims/HB_mens_sims.csv")
FX_sims_m <- read_csv("App-1/data/rostersims/FX_mens_sims.csv")
PB_sims_m <- read_csv("App-1/data/rostersims/PB_mens_sims.csv")
VT_sims_m <- read_csv("App-1/data/rostersims/VT_mens_sims.csv")
PH_sims_m <- read_csv("App-1/data/rostersims/PH_mens_sims.csv")
SR_sims_m <- read_csv("App-1/data/rostersims/SR_mens_sims.csv")

# Define a function to replace NA with 0 and drop the average score column
prepare_df <- function(df) {
  df %>% 
    mutate(across(starts_with("Score"), ~ replace_na(., 0)))
}

HB_sims_prepared_m <- prepare_df(HB_sims_m)
FX_sims_prepared_m <- prepare_df(FX_sims_m)
PB_sims_prepared_m <- prepare_df(PB_sims_m)
VT_sims_prepared_m <- prepare_df(VT_sims_m)
PH_sims_prepared_m <- prepare_df(PH_sims_m)
SR_sims_prepared_m <- prepare_df(SR_sims_m)

# Use left joins to combine the dataframes
combined_AA_df_m <- HB_sims_prepared_m %>%
  left_join(FX_sims_prepared_m, by = c("FirstName", "LastName", "Country")) %>%
  left_join(PB_sims_prepared_m, by = c("FirstName", "LastName", "Country")) %>%
  left_join(VT_sims_prepared_m, by = c("FirstName", "LastName", "Country")) %>% 
  left_join(PH_sims_prepared_m, by = c("FirstName", "LastName", "Country")) %>% 
  left_join(SR_sims_prepared_m, by = c("FirstName", "LastName", "Country")) 
```

```{r sum-across-events-men}
# Create a vector of column indices to sum
original_data <- combined_AA_df_m[, -(1:3)]
names <- combined_AA_df_m[, (1:3)]


# Sum every 1000th column and store the result in the condensed dataframe
condensed_data <- data.frame(matrix(NA, nrow = nrow(original_data), ncol = 401))

# Loop through each group of 1000 columns
for (i in 1:401) {
  # Identify the columns in the current group
  current_group_columns <- c(i, i + 400,i+800,i+1200,i+1600,i+2000)
  #print(current_group_columns)
  # Sum the values across the columns in the current group
  condensed_data[, i] <- rowSums(original_data[, current_group_columns], na.rm = TRUE)
}

# Rename the columns of the condensed dataframe
colnames(condensed_data) <- paste0("Condensed_Column_", 1:ncol(condensed_data))

# Print or use the condensed dataframe as needed
combinedfinalAA_m <- cbind(names,condensed_data)

columns_to_average <- combinedfinalAA_m[, -(1:3)]

# Calculate the row-wise mean for the selected columns
combinedfinalAA_m$AverageScore <- rowMeans(columns_to_average, na.rm = TRUE)

write.csv(combinedfinalAA_m, "App-1/data/rostersims/AA_mens_sims.csv", row.names = FALSE)
```






### Ranks and Percentages

```{r average rank}

# Assuming 'simulations_data' is the dataframe containing the simulation data
# with columns for name, country, and 100 simulation scores, and an average simulation score

compute_average_rank <- function(simulations_data) {
  # Select only the columns with simulation scores
  score_columns <- simulations_data %>% select(starts_with(c("Score_","Condensed_Column_")))
  
  # Initialize a dataframe to store the ranks
  rank_data <- simulations_data %>%
    mutate(across(starts_with(c("Score_","Condensed_Column_")), ~rank(-.x, ties.method = "min")), na.rm = TRUE)
  
  # Compute the average rank for each gymnast
  rank_data$AverageRank <- rowMeans(rank_data %>% select(starts_with(c("Score_","Condensed_Column_"))))
  
  rankdata2 <- rank_data
  # Compute the number of simulations
  num_simulations <- ncol(score_columns)


  simulations_data <- simulations_data %>%
    mutate(
      QualifyPercentage = 0,
      GoldPercentage = 0,
      SilverPercentage = 0,
      BronzePercentage = 0
    )

  for (n in 2:num_simulations) {
    if (simulations_data$AverageScore[1]>45){rank_col <- paste0("Condensed_Column_", n)}
    else{
      rank_col <- paste0("Score_", n)
    }
    
    rankdata2 <- rankdata2 %>%
      arrange(!!sym(rank_col)) %>%
      mutate(TempRank = 1:n())
    
    
    # Adjust the top 8 ranks to account for the country restriction
    top_8_ranks <- rankdata2 %>%
      group_by(Country) %>%
      mutate(CountryCount = row_number()) %>%
      filter(CountryCount <= 2) %>%
      ungroup() %>%
      arrange(TempRank) %>%
      slice(1:8)

    # Update the Top10Percentage and medal percentages
    for (i in 1:nrow(simulations_data)) {
      athlete <- simulations_data[i, c("FirstName", "LastName")]
      athlete_rank <- top_8_ranks %>%
        filter(FirstName == athlete$FirstName, LastName == athlete$LastName)

      #return(athlete_rank)
      if (nrow(athlete_rank) > 0) {
        temp_rank <- athlete_rank$TempRank
        
        if (temp_rank <= 8) simulations_data$QualifyPercentage[i] <- simulations_data$QualifyPercentage[i] + 1 / num_simulations * 100
        if (temp_rank == 1) simulations_data$GoldPercentage[i] <- simulations_data$GoldPercentage[i] + 1 / num_simulations * 100
        if (temp_rank == 2) simulations_data$SilverPercentage[i] <- simulations_data$SilverPercentage[i] + 1 / num_simulations * 100
        if (temp_rank == 3) simulations_data$BronzePercentage[i] <- simulations_data$BronzePercentage[i] + 1 / num_simulations * 100
      }
    }
  }

  # Add the AverageRank column to the original dataframe
  simulations_data$AverageRank <- rank_data$AverageRank

  simulations_data <- simulations_data %>%
    select(FirstName, LastName, Country, AverageScore, AverageRank, QualifyPercentage, GoldPercentage, SilverPercentage, BronzePercentage)%>% mutate(across(where(is.numeric), ~round(., 2)))
  
  return(simulations_data)
}


```

```{r}
#AA_mens_sims <- read.csv("App-1/data/rostersims/AA_mens_sims.csv")
#testsss <- compute_average_rank(AA_mens_sims)


```



```{r women ranks}
# List of women's events
women_events <- c("BB", "UB", "FX", "VT", "AA")


# Loop over women's events
for (event_name in women_events) {
  # Generate dataframe name
  sims_path <- paste0("App-1/data/rostersims/",event_name, "_womens_sims.csv")
  dataframe_name <- paste0(event_name, "_womens_predictions")
  sims_df <- read.csv(sims_path)
  # Run the function for the specific event and save the results
  tempsims <- assign(dataframe_name, compute_average_rank(sims_df))
  path <- paste0("App-1/data/rostersims/",dataframe_name,".csv")
  write.csv(tempsims, path, row.names = FALSE)
}


```

```{r}
#something <- compute_average_rank(FX_sims)
#temp_rank <- something$TempRank

#if (temp_rank<=8){print("ok")}
```


```{r men ranks}
# List of women's events
men_events <- c("FX", "HB", "PB", "PH","SR","VT", "AA")


# Loop over women's events
for (event_name in men_events) {
  # Generate dataframe name
  sims_path <- paste0("App-1/data/rostersims/",event_name, "_mens_sims.csv")
  dataframe_name <- paste0(event_name, "_mens_predictions")
  sims_df <- read.csv(sims_path)
  # Run the function for the specific event and save the results
  tempsims <- assign(dataframe_name, compute_average_rank(sims_df))
  path <- paste0("App-1/data/rostersims/",dataframe_name,".csv")
  write.csv(tempsims, path, row.names = FALSE)
}


```

## Calculating Team Podium Chances


```{r teamsims}
process_dataset <- function(nm, dataset) {
    # Step 1: Filter for 5 names
    #fix_data
    
    fixed_data <- nfix(dataset)
    #return(fixed_data)
    
    filtered_dataset <- fixed_data[fixed_data$FullName %in% nm, ]
    #return(filtered_dataset)
    # Step 2: Sort by average points
    sorted_dataset <- filtered_dataset %>% 
      arrange(desc(AverageScore)) %>% 
      head(3)
    
    #return(sorted_dataset)
    # Step 3: Aggregate the top 3 scores into one row
    aggregated_row <- sorted_dataset %>%
      mutate(across(4:403, ~ sum(.))) %>% 
      head(1)
    
    return(aggregated_row)
  }
  
  teamsims <- function(gymnasts,gender) {
    HB_sims_m <- read.csv("App-1/data/rostersims/HB_mens_sims.csv")
    PH_sims_m <- read.csv("App-1/data/rostersims/PH_mens_sims.csv")
    PB_sims_m <- read.csv("App-1/data/rostersims/PB_mens_sims.csv")
    FX_sims_m <- read.csv("App-1/data/rostersims/FX_mens_sims.csv")
    VT_sims_m <- read.csv("App-1/data/rostersims/VT_mens_sims.csv")
    SR_sims_m <- read.csv("App-1/data/rostersims/SR_mens_sims.csv")
    
    BB_sims_w <- read.csv("App-1/data/rostersims/BB_womens_sims.csv")
    VT_sims_w <- read.csv("App-1/data/rostersims/VT_womens_sims.csv")
    UB_sims_w <- read.csv("App-1/data/rostersims/UB_womens_sims.csv")
    FX_sims_w <- read.csv("App-1/data/rostersims/FX_womens_sims.csv")
    
    
    if (gender == "Men") {
      dataevents <- list(HB_sims_m,PH_sims_m,PB_sims_m,FX_sims_m,VT_sims_m,SR_sims_m) 
    }
    else{
      dataevents <- list(BB_sims_w,VT_sims_w,UB_sims_w,FX_sims_w)
    }
    
    
    #print(nm)
    pds <- data.frame()
    
    for (event_data in dataevents) {
      e <- process_dataset(gymnasts, event_data)
      #return(e)
      pds <- rbind(pds,e)
      
    }
    
    # Combine the results into one big dataframe
    
    final_result <- pds %>% 
      mutate(across(4:403, ~ sum(.))) %>% 
      head(1)
    
    return(final_result)
    
  }
```


```{r mencompile}

menteams <- list(CAN_m, CHN_m, GER_m, GBR_m, ITA_m, JPN_m, NED_m, ESP_m, SUI_m, TUR_m, UKR_m, USA_m)
allmen <- data.frame()
for (mt in menteams){
  ts <- teamsims(mt,"Men")
  allmen <- rbind(allmen,ts)
}

allmen <- allmen %>% 
  select(-FirstName,-LastName,-FullName)


```

```{r womencompile}
womenteams <- list(AUS_w, BRA_w, CAN_w, CHN_w, FRA_w, GBR_w, ITA_w, JPN_w, NED_w, ROU_w, KOR_w, USA_w)
allwomen <- data.frame()
for (wt in womenteams){
  tsw <- teamsims(wt,"Women")
  allwomen <- rbind(allwomen,tsw)
}

allwomen <- allwomen %>% 
  select(-FirstName,-LastName,-FullName)
```



```{r team rank}

# Assuming 'simulations_data' is the dataframe containing the simulation data
# with columns for name, country, and 100 simulation scores, and an average simulation score

compute_average_rank_team <- function(simulations_data) {
  # Select only the columns with simulation scores
  score_columns <- simulations_data %>% select(starts_with(c("Score_","Condensed_Column_")))
  
  simulations_data$AverageScore <- rowMeans(simulations_data %>% select(starts_with(c("Score_","Condensed_Column_"))))
  
  # Initialize a dataframe to store the ranks
  rank_data <- simulations_data %>%
    mutate(across(starts_with(c("Score_","Condensed_Column_")), ~rank(-.x, ties.method = "min")), na.rm = TRUE)
  
  # Compute the average rank for each gymnast
  rank_data$AverageRank <- rowMeans(rank_data %>% select(starts_with(c("Score_","Condensed_Column_"))))
  
  rankdata2 <- rank_data
  # Compute the number of simulations
  num_simulations <- ncol(score_columns)


  simulations_data <- simulations_data %>%
    mutate(
      QualifyPercentage = 0,
      GoldPercentage = 0,
      SilverPercentage = 0,
      BronzePercentage = 0
    )

  for (n in 2:num_simulations) {
    
    rank_col <- paste0("Score_", n)
    
    
    rankdata2 <- rankdata2 %>%
      arrange(!!sym(rank_col)) %>%
      mutate(TempRank = 1:n())

    # Update the Top10Percentage and medal percentages
    for (i in 1:nrow(simulations_data)) {
      athlete <- simulations_data[i, "Country"]
      #return(athlete)
      athlete_rank <- rankdata2 %>%
        filter(Country == athlete)

      #return(athlete_rank)
      if (nrow(athlete_rank) > 0) {
        temp_rank <- athlete_rank$TempRank
        if (length(temp_rank)>1){
          print(temp_rank)
          return(athlete_rank)}
        if (temp_rank <= 8) simulations_data$QualifyPercentage[i] <- simulations_data$QualifyPercentage[i] + 1 / num_simulations * 100
        if (temp_rank == 1) simulations_data$GoldPercentage[i] <- simulations_data$GoldPercentage[i] + 1 / num_simulations * 100
        if (temp_rank == 2) simulations_data$SilverPercentage[i] <- simulations_data$SilverPercentage[i] + 1 / num_simulations * 100
        if (temp_rank == 3) simulations_data$BronzePercentage[i] <- simulations_data$BronzePercentage[i] + 1 / num_simulations * 100
      }
    }
  }

  # Add the AverageRank column to the original dataframe
  simulations_data$AverageRank <- rank_data$AverageRank
  simulations_data <- simulations_data %>%
    select(Country, AverageScore, AverageRank, QualifyPercentage, GoldPercentage, SilverPercentage, BronzePercentage)%>% mutate(across(where(is.numeric), ~round(., 2)))
  
  return(simulations_data)
}


```

```{r}
teamPredMen <- compute_average_rank_team(allmen)
teamPredWomen <- compute_average_rank_team(allwomen)
```


