```{r}
#| label: load-libraries

library(readr)
library(tidyverse)
library(dplyr)
library(stringr)
library(lubridate)
```

```{r}
#| label: load-data
data_2022_2023 <- read_csv("Data/data_2022_2023.csv")
data_2017_2021 <- read_csv("Data/data_2017_2021.csv")

#DO NOT CHANGE ORDER

data_2022_2023$Apparatus[data_2022_2023$Apparatus == "VT2"] <- "VT"
data_2022_2023$Apparatus[data_2022_2023$Apparatus == "VT1"] <- "VT"
data_2022_2023$Apparatus[data_2022_2023$Apparatus == "UE"] <- "UB"

data_2022_2023$Penalty[is.na(data_2022_2023$Penalty)] <- 0

#Girls filtering for middle name
data_2022_2023$FirstName[data_2022_2023$FirstName == "Joscelyn Michelle"] <- "Joscelyn"
data_2022_2023$FirstName[data_2022_2023$FirstName == "Nola Rhianne"] <- "Nola"

#Guys filtering for middle name
data_2022_2023$FirstName[data_2022_2023$FirstName == "Taylor Troy"] <- "Taylor"
data_2022_2023$FirstName[data_2022_2023$FirstName == "Joshua Andrew"] <- "Joshua"
data_2022_2023$FirstName[data_2022_2023$FirstName == "Yul Kyung Tae"] <- "Yul"
data_2022_2023$FirstName[data_2022_2023$FirstName == "Curran Michael"] <- "Curran"
data_2022_2023$FirstName[data_2022_2023$FirstName == "Frederick Nathaniel"] <- "Frederick"
data_2022_2023$FirstName[data_2022_2023$FirstName == "Ian Hunter"] <- "Ian"
data_2022_2023$FirstName[data_2022_2023$FirstName == "Shane Michael"] <- "Shane"
data_2022_2023$FirstName[data_2022_2023$FirstName == "Khoi Alexander"] <- "Khoi"

data_2022_2023$FirstName[data_2022_2023$FirstName == "Yunus Emre"] <- "Yunus"

data_2022_2023$FirstName[data_2022_2023$FirstName == "Yuan-Hsi"] <- "Yuan Hsi"

data_2022_2023$FirstName[data_2022_2023$FirstName == "Yu-Jan"] <- "Yu Jan"

data_2022_2023$LastName[data_2022_2023$LastName == "VILLAVERDE MEDEROS"] <- "VILLAVERDE"

data_2022_2023$LastName[data_2022_2023$LastName == "VALENZUELA ASTUDILLO"] <- "VALENZUELA"

data_2022_2023$FirstName[data_2022_2023$FirstName == "Yiseth Eliana"] <- "Yiseth"
data_2022_2023$FirstName[data_2022_2023$FirstName == "Yi-Chen"] <- "Yi Chen"
data_2022_2023$FirstName[data_2022_2023$FirstName == "Yi-Chun"] <- "Yi Chun"

data_2022_2023$FirstName[data_2022_2023$FirstName == "Yefferson Gregorio"] <- "Yefferson"
data_2022_2023$LastName[data_2022_2023$LastName == "ANTON YEGUEZ"] <- "ANTON"

data_2022_2023$LastName[data_2022_2023$LastName == "ANTON YEGUEZ"] <- "ANTON"

data_2022_2023$FirstName[data_2022_2023$FirstName == "Wout Johan Alexander"] <- "Wout"

data_2022_2023$FirstName[data_2022_2023$FirstName == "Wilfry Manuel"] <- "Wilfry"

data_2022_2023$FirstName[data_2022_2023$FirstName == "Wei-Sheng"] <- "Wei Sheng"

data_2022_2023$FirstName[(data_2022_2023$Competition == "BIRMINGHAM 2022 Commonwealth Games") & (is.na(data_2022_2023$LastName))] <- "Kate"

data_2022_2023$LastName[(data_2022_2023$Competition == "BIRMINGHAM 2022 Commonwealth Games") & (is.na(data_2022_2023$LastName))] <- "MCDONALD"

data_2022_2023$FirstName[data_2022_2023$LastName == "SOUZA BITENCOU"] <- "Lucas"
data_2022_2023$LastName[data_2022_2023$LastName == "SOUZA BITENCOU"] <- "BITENCOURT"

data_2022_2023$LastName[data_2022_2023$LastName == "DE JESUS DOS SANTOS"] <- "JESUS SANTOS"

data_2022_2023$FirstName[data_2022_2023$LastName == "JESUS SANT"] <- "Melanie"
data_2022_2023$LastName[data_2022_2023$LastName == "JESUS SANT"] <- "JESUS SANTOS"

data_2022_2023$LastName[data_2022_2023$LastName == "ELPITIYA BADALGE DONA"] <- "GEHANI"
data_2022_2023$FirstName[data_2022_2023$FirstName == "Milka Gehani"] <- "Milka"

data_2022_2023$FirstName[data_2022_2023$LastName == "ELPITIYA BADALG D"] <- "Milka"

data_2022_2023$LastName[data_2022_2023$LastName == "ELPITIYA BADALG D"] <- "GEHANI"

data_2022_2023$FirstName[(data_2022_2023$Competition == "2022 51st FIG Artistic Gymnastics World Championship") & (is.na(data_2022_2023$LastName))] <- "Kate"

data_2022_2023$LastName[(data_2022_2023$Competition == "2022 51st FIG Artistic Gymnastics World Championship") & (is.na(data_2022_2023$LastName))] <- "MCDONALD"

data_2022_2023$FirstName[(data_2022_2023$Competition == "2023 Varna World Challenge Cup") & (is.na(data_2022_2023$LastName))] <- "Daria"

data_2022_2023$LastName[(data_2022_2023$Competition == "2023 Varna World Challenge Cup") & (is.na(data_2022_2023$LastName))] <- "HARTMANN"

data_2022_2023$FirstName[data_2022_2023$LastName == "ABIYURAFI"] <- "Abiyu"
data_2022_2023$LastName[data_2022_2023$LastName == "ABIYURAFI"] <- "Rafi"


#Konnor McClain should not be considered, she has hand surgery

```

```{r}
#| label: usa-filter-data

usa_data_2022_2023 <- data_2022_2023 |>
  filter(`Country` == "USA")

usa_data_2017_2021 <- data_2017_2021 |>
  filter(`Country` == "USA")

data_2022_2023 <- rbind(data_2022_2023, data_2017_2021)

data_2022_2023$Apparatus[data_2022_2023$Apparatus == "VT2"] <- "VT"
data_2022_2023$Apparatus[data_2022_2023$Apparatus == "VT1"] <- "VT"

```

```{r date_things}

# Assuming your dataframe is called data_2022_2023 and the column with dates is "Date"

# Step 1: Create a function to extract the second date from each string
extract_second_date <- function(date_string) {
  parts <- str_extract_all(date_string, "\\d{1,2}\\s[A-Za-z]+\\s\\d{4}")[[1]]
  if (length(parts) == 2) {
    # If there are two dates, return the second one
    return(parts[2])
  } else if (length(parts) == 1) {
    # If there is only one date, return it
    return(parts[1])
  } else {
    return(NA)
  }
}

# Step 2: Apply the function to the Date column and convert to Date objects
data_2022_2023 <- data_2022_2023 %>%
  mutate(
    SecondDateStr = sapply(Date, extract_second_date),
    SecondDate = dmy(SecondDateStr)
  )

# Define the end date
end_date <- dmy("01-01-2024")

# Calculate the number of days from the SecondDate to the end date
data_2022_2023 <- data_2022_2023 %>%
  mutate(
    DaysUntil2024 = as.integer(end_date - SecondDate)
  )

# Inspect the changes
head(data_2022_2023)

```

```{r standardize_scores}
data_2022_2023 <- data_2022_2023 %>%
  group_by(Apparatus, Gender) %>%
  mutate(
    StandardizedScore = (Score - mean(Score, na.rm = TRUE)) / sd(Score, na.rm = TRUE)
  ) %>%
  ungroup()
```

```{r create-sampling-dist}
final_rows_full <- data_2022_2023[grep("final|Final", data_2022_2023$Round), ]
less_than_180_rows <- data_2022_2023[data_2022_2023$DaysUntil2024 < 180, ]
between_180_540_rows <- data_2022_2023[data_2022_2023$DaysUntil2024 >= 180 & data_2022_2023$DaysUntil2024 <= 540, ]

sampling_data_2022_2023 <- rbind(data_2022_2023, final_rows_full, less_than_180_rows, less_than_180_rows, between_180_540_rows)

sampling_usa_data_2022_2023_f <-  sampling_data_2022_2023 |>
  filter(`Country` == "USA") |>
  filter(Gender == "w")

sampling_usa_data_2022_2023_m <-  sampling_data_2022_2023 |>
  filter(`Country` == "USA") |>
  filter(Gender == "m")
```

```{r}
#Number of simulations
nsimulation <- 1000
```

```{r overall simulation women, eval = FALSE}
set.seed(123)

# Identify unique gymnasts
unique_gymnasts <- unique(sampling_usa_data_2022_2023_f[, c("FirstName", "LastName")])

# Create a new dataframe to store sampled scores and overall scores
sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric()
)

n_iterations_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score_1 = numeric()
)
# First iteration
# Loop through each unique gymnast
for (i in 1:nrow(unique_gymnasts)) {
  # Extract the current gymnast's information
  current_gymnast <- unique_gymnasts[i, ]
  
  # Subset the data for the current gymnast
  subset_data <- sampling_usa_data_2022_2023_f[sampling_usa_data_2022_2023_f$FirstName == current_gymnast$FirstName & 
                                sampling_usa_data_2022_2023_f$LastName == current_gymnast$LastName, ]
  
  # Sample scores for each apparatus
  BB_subset_data <- subset_data[subset_data$Apparatus == "BB",]
  if (nrow(BB_subset_data) == 0) {
  # If the subset is empty, set the sampled value to 0
    sampled_BB_score <- 0
  } 
  else {
    # If the subset is not empty, sample the "Score" column
    sampled_BB_score <- sample(BB_subset_data$Score, size = 1)
  }
  FX_subset_data <- subset_data[subset_data$Apparatus == "FX",]
  if (nrow(FX_subset_data) == 0) {
  # If the subset is empty, set the sampled value to 0
    sampled_FX_score <- 0
  } 
  else {
    # If the subset is not empty, sample the "Score" column
    sampled_FX_score <- sample(FX_subset_data$Score, size = 1)
  }
  VT_subset_data <- subset_data[subset_data$Apparatus == "VT",]
  if (nrow(VT_subset_data) == 0) {
  # If the subset is empty, set the sampled value to 0
    sampled_VT_score <- 0
  } 
  else {
    # If the subset is not empty, sample the "Score" column
    sampled_VT_score <- sample(VT_subset_data$Score, size = 1)
  }
  UB_subset_data <- subset_data[subset_data$Apparatus == "UB",]
  if (nrow(UB_subset_data) == 0) {
  # If the subset is empty, set the sampled value to 0
    sampled_UB_score <- 0
  } 
  else {
    # If the subset is not empty, sample the "Score" column
    sampled_UB_score <- sample(UB_subset_data$Score, size = 1)
  }
  
  # Calculate overall score
  overall_score <- sampled_BB_score + sampled_FX_score + sampled_VT_score + sampled_UB_score
  
  # Create a data frame for the current gymnast's sampled scores and overall score
  current_data <- data.frame(
    FirstName = current_gymnast$FirstName,
    LastName = current_gymnast$LastName,
    Score_1 = overall_score,
    stringsAsFactors = FALSE
  )
  
  # Append the current data to the overall sampled_scores_data dataframe
  sampled_scores_data <- rbind(sampled_scores_data, current_data)
}

n_iterations_data = sampled_scores_data
#sampled_scores_data = sampled_scores_data[order(-sampled_scores_data$Score), ]

# View the dataframe with sampled scores and overall scores
#print(sampled_scores_data)

for(n in 2:nsimulation){
  sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric())
  for (i in 1:nrow(unique_gymnasts)) {
    # Extract the current gymnast's information
    current_gymnast <- unique_gymnasts[i, ]
    
    # Subset the data for the current gymnast
    subset_data <- sampling_usa_data_2022_2023_f[sampling_usa_data_2022_2023_f$FirstName == current_gymnast$FirstName & 
                                  sampling_usa_data_2022_2023_f$LastName == current_gymnast$LastName, ]
    
    # Sample scores for each apparatus
    BB_subset_data <- subset_data[subset_data$Apparatus == "BB",]
    if (nrow(BB_subset_data) == 0) {
    # If the subset is empty, set the sampled value to 0
      sampled_BB_score <- 0
    } 
    else {
      # If the subset is not empty, sample the "Score" column
      sampled_BB_score <- sample(BB_subset_data$Score, size = 1)
    }
    FX_subset_data <- subset_data[subset_data$Apparatus == "FX",]
    if (nrow(FX_subset_data) == 0) {
    # If the subset is empty, set the sampled value to 0
      sampled_FX_score <- 0
    } 
    else {
      # If the subset is not empty, sample the "Score" column
      sampled_FX_score <- sample(FX_subset_data$Score, size = 1)
    }
    VT_subset_data <- subset_data[subset_data$Apparatus == "VT",]
    if (nrow(VT_subset_data) == 0) {
    # If the subset is empty, set the sampled value to 0
      sampled_VT_score <- 0
    } 
    else {
      # If the subset is not empty, sample the "Score" column
      sampled_VT_score <- sample(VT_subset_data$Score, size = 1)
    }
    UB_subset_data <- subset_data[subset_data$Apparatus == "UB",]
    if (nrow(UB_subset_data) == 0) {
    # If the subset is empty, set the sampled value to 0
      sampled_UB_score <- 0
    } 
    else {
      # If the subset is not empty, sample the "Score" column
      sampled_UB_score <- sample(UB_subset_data$Score, size = 1)
    }
    
    # Calculate overall score
    overall_score <- sampled_BB_score + sampled_FX_score + sampled_VT_score + sampled_UB_score
    
    # Create a data frame for the current gymnast's sampled scores and overall score
    current_data <- data.frame(
      FirstName = current_gymnast$FirstName,
      LastName = current_gymnast$LastName,
      Score = overall_score,
      stringsAsFactors = FALSE
    )
    
    # Append the current data to the overall sampled_scores_data dataframe
    sampled_scores_data <- rbind(sampled_scores_data, current_data)
  }
  n_iterations_data <- cbind(n_iterations_data, sampled_scores_data$Score)
  colnames(n_iterations_data)[colnames(n_iterations_data) == "sampled_scores_data$Score"] <- paste("Score_", n, sep = "")
}

columns_to_average <- n_iterations_data[, -(1:2)]

# Calculate the row-wise mean for the selected columns
n_iterations_data$AverageScore <- rowMeans(columns_to_average, na.rm = TRUE)

final_average_df <- n_iterations_data[, c(1, 2, ncol(n_iterations_data))]

final_average_df = final_average_df[order(-final_average_df$AverageScore), ]
overall_women <- final_average_df
print(final_average_df)
```

```{r BB simulation women, eval = FALSE}

set.seed(123)

# Identify unique gymnasts
unique_gymnasts <- unique(sampling_usa_data_2022_2023_f[, c("FirstName", "LastName")])

# Create a new dataframe to store sampled scores and overall scores
sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric()
)

n_iterations_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score_1 = numeric()
)
# First iteration
# Loop through each unique gymnast
for (i in 1:nrow(unique_gymnasts)) {
  # Extract the current gymnast's information
  current_gymnast <- unique_gymnasts[i, ]
  
  # Subset the data for the current gymnast
  subset_data <- sampling_usa_data_2022_2023_f[sampling_usa_data_2022_2023_f$FirstName == current_gymnast$FirstName & 
                                sampling_usa_data_2022_2023_f$LastName == current_gymnast$LastName, ]
  
  # Sample scores for each apparatus
  BB_subset_data <- subset_data[subset_data$Apparatus == "BB",]
  if (nrow(BB_subset_data) == 0) {
  # If the subset is empty, set the sampled value to 0
    sampled_BB_score <- 0
  } 
  else {
    # If the subset is not empty, sample the "Score" column
    sampled_BB_score <- sample(BB_subset_data$Score, size = 1)
  }
  
  # Create a data frame for the current gymnast's sampled scores and overall score
  current_data <- data.frame(
    FirstName = current_gymnast$FirstName,
    LastName = current_gymnast$LastName,
    Score_1 = sampled_BB_score,
    stringsAsFactors = FALSE
  )
  
  # Append the current data to the overall sampled_scores_data dataframe
  sampled_scores_data <- rbind(sampled_scores_data, current_data)
}

n_iterations_data = sampled_scores_data
#sampled_scores_data = sampled_scores_data[order(-sampled_scores_data$Score), ]

# View the dataframe with sampled scores and overall scores
#print(sampled_scores_data)

for(n in 2:nsimulation){
  sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric())
  for (i in 1:nrow(unique_gymnasts)) {
    # Extract the current gymnast's information
    current_gymnast <- unique_gymnasts[i, ]
    
    # Subset the data for the current gymnast
    subset_data <- sampling_usa_data_2022_2023_f[sampling_usa_data_2022_2023_f$FirstName == current_gymnast$FirstName & 
                                  sampling_usa_data_2022_2023_f$LastName == current_gymnast$LastName, ]
    
    # Sample scores for each apparatus
    BB_subset_data <- subset_data[subset_data$Apparatus == "BB",]
    if (nrow(BB_subset_data) == 0) {
    # If the subset is empty, set the sampled value to 0
      sampled_BB_score <- 0
    } 
    else {
      # If the subset is not empty, sample the "Score" column
      sampled_BB_score <- sample(BB_subset_data$Score, size = 1)
    }
    
    # Create a data frame for the current gymnast's sampled scores and overall score
    current_data <- data.frame(
      FirstName = current_gymnast$FirstName,
      LastName = current_gymnast$LastName,
      Score = sampled_BB_score,
      stringsAsFactors = FALSE
    )
    
    # Append the current data to the overall sampled_scores_data dataframe
    sampled_scores_data <- rbind(sampled_scores_data, current_data)
  }
  n_iterations_data <- cbind(n_iterations_data, sampled_scores_data$Score)
  colnames(n_iterations_data)[colnames(n_iterations_data) == "sampled_scores_data$Score"] <- paste("Score_", n, sep = "")
}

columns_to_average <- n_iterations_data[, -(1:2)]

# Calculate the row-wise mean for the selected columns
n_iterations_data$AverageScore <- rowMeans(columns_to_average, na.rm = TRUE)

final_average_df <- n_iterations_data[, c(1, 2, ncol(n_iterations_data))]

final_average_df = final_average_df[order(-final_average_df$AverageScore), ]
print(final_average_df)
overall_BB_women <- final_average_df
```

```{r BB-simulation-t-dist-women, eval = FALSE}

set.seed(123)

# Identify unique gymnasts
unique_gymnasts <- unique(sampling_usa_data_2022_2023_f[, c("FirstName", "LastName")])

# Create a new dataframe to store sampled scores
n_iterations_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score_1 = numeric()
)

# Assume we have a variable 'nsimulation' that defines the number of simulations
for (n in 1:nsimulation) {
  sampled_scores_data <- data.frame(
    FirstName = character(),
    LastName = character(),
    Score = numeric()
  )

  for (i in 1:nrow(unique_gymnasts)) {
    # Extract the current gymnast's information
    current_gymnast <- unique_gymnasts[i, ]

    # Subset the data for the current gymnast
    subset_data <- sampling_usa_data_2022_2023_f[sampling_usa_data_2022_2023_f$FirstName == current_gymnast$FirstName & 
                                sampling_usa_data_2022_2023_f$LastName == current_gymnast$LastName, ]

    # Sample scores for each apparatus
    BB_subset_data <- subset_data[subset_data$Apparatus == "BB",]
    
    # Check if the gymnast has at least 5 rows of data
    if (nrow(BB_subset_data) < 5) {
      next  # Skip to the next gymnast
    }
    
    if (nrow(BB_subset_data) == 0) {
      # If the subset is empty, set the sampled value to 0
      sampled_BB_score <- 0
    } else {
      # Calculate mean and standard deviation
      mean_score <- mean(BB_subset_data$Score)
      sd_score <- sd(BB_subset_data$Score)
      max_cutoff <- max(BB_subset_data$Score) + 0.3
      
      # Initialize sampled_BB_score
      sampled_BB_score <- NA
      
      # Sample from the t-distribution until the score is less than or equal to max_cutoff
      while(is.na(sampled_BB_score) || sampled_BB_score > max_cutoff) {
        df <- max(nrow(BB_subset_data) - 1, 1) # to avoid df being zero
        sampled_BB_score <- mean_score + rt(1, df) * sd_score
      }
    }

    # Create a data frame for the current gymnast's sampled scores
    current_data <- data.frame(
      FirstName = current_gymnast$FirstName,
      LastName = current_gymnast$LastName,
      Score = sampled_BB_score,
      stringsAsFactors = FALSE
    )

    # Append the current data to the overall sampled_scores_data dataframe
    sampled_scores_data <- rbind(sampled_scores_data, current_data)
  }
  
  # Combine the scores into n_iterations_data
  if (n == 1) {
    n_iterations_data <- sampled_scores_data
  } else {
    n_iterations_data <- cbind(n_iterations_data, sampled_scores_data$Score)
    colnames(n_iterations_data)[ncol(n_iterations_data)] <- paste("Score_", n, sep = "")
  }
}

# Calculate the average scores
columns_to_average <- n_iterations_data[, -(1:2)]
n_iterations_data$AverageScore <- rowMeans(columns_to_average, na.rm = TRUE)
final_average_df <- n_iterations_data[, c(1, 2, ncol(n_iterations_data))]
final_average_df = final_average_df[order(-final_average_df$AverageScore), ]
print(final_average_df)
```

```{r FX simulation women, eval = FALSE}
set.seed(123)

# Identify unique gymnasts
unique_gymnasts <- unique(sampling_usa_data_2022_2023_f[, c("FirstName", "LastName")])

# Create a new dataframe to store sampled scores and overall scores
sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric()
)

n_iterations_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score_1 = numeric()
)
# First iteration
# Loop through each unique gymnast
for (i in 1:nrow(unique_gymnasts)) {
  # Extract the current gymnast's information
  current_gymnast <- unique_gymnasts[i, ]
  
  # Subset the data for the current gymnast
  subset_data <- sampling_usa_data_2022_2023_f[sampling_usa_data_2022_2023_f$FirstName == current_gymnast$FirstName & 
                                sampling_usa_data_2022_2023_f$LastName == current_gymnast$LastName, ]
  
  # Sample scores for each apparatus
  FX_subset_data <- subset_data[subset_data$Apparatus == "FX",]
  if (nrow(FX_subset_data) == 0) {
  # If the subset is empty, set the sampled value to 0
    sampled_FX_score <- 0
  } 
  else {
    # If the subset is not empty, sample the "Score" column
    sampled_FX_score <- sample(FX_subset_data$Score, size = 1)
  }
  
  # Create a data frame for the current gymnast's sampled scores and overall score
  current_data <- data.frame(
    FirstName = current_gymnast$FirstName,
    LastName = current_gymnast$LastName,
    Score_1 = sampled_FX_score,
    stringsAsFactors = FALSE
  )
  
  # Append the current data to the overall sampled_scores_data dataframe
  sampled_scores_data <- rbind(sampled_scores_data, current_data)
}

n_iterations_data = sampled_scores_data
#sampled_scores_data = sampled_scores_data[order(-sampled_scores_data$Score), ]

# View the dataframe with sampled scores and overall scores
#print(sampled_scores_data)

for(n in 2:nsimulation){
  sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric())
  for (i in 1:nrow(unique_gymnasts)) {
    # Extract the current gymnast's information
    current_gymnast <- unique_gymnasts[i, ]
    
    # Subset the data for the current gymnast
    subset_data <- sampling_usa_data_2022_2023_f[sampling_usa_data_2022_2023_f$FirstName == current_gymnast$FirstName & 
                                  sampling_usa_data_2022_2023_f$LastName == current_gymnast$LastName, ]
    
    # Sample scores for each apparatus
    FX_subset_data <- subset_data[subset_data$Apparatus == "FX",]
    if (nrow(FX_subset_data) == 0) {
    # If the subset is empty, set the sampled value to 0
      sampled_FX_score <- 0
    } 
    else {
      # If the subset is not empty, sample the "Score" column
      sampled_FX_score <- sample(FX_subset_data$Score, size = 1)
    }
    
    # Create a data frame for the current gymnast's sampled scores and overall score
    current_data <- data.frame(
      FirstName = current_gymnast$FirstName,
      LastName = current_gymnast$LastName,
      Score = sampled_FX_score,
      stringsAsFactors = FALSE
    )
    
    # Append the current data to the overall sampled_scores_data dataframe
    sampled_scores_data <- rbind(sampled_scores_data, current_data)
  }
  n_iterations_data <- cbind(n_iterations_data, sampled_scores_data$Score)
  colnames(n_iterations_data)[colnames(n_iterations_data) == "sampled_scores_data$Score"] <- paste("Score_", n, sep = "")
}

columns_to_average <- n_iterations_data[, -(1:2)]

# Calculate the row-wise mean for the selected columns
n_iterations_data$AverageScore <- rowMeans(columns_to_average, na.rm = TRUE)

final_average_df <- n_iterations_data[, c(1, 2, ncol(n_iterations_data))]

final_average_df = final_average_df[order(-final_average_df$AverageScore), ]
overall_FX_women <- final_average_df
print(final_average_df)
```

```{r VT simulation women, eval = FALSE}
set.seed(123)

# Identify unique gymnasts
unique_gymnasts <- unique(sampling_usa_data_2022_2023_f[, c("FirstName", "LastName")])

# Create a new dataframe to store sampled scores and overall scores
sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric()
)

n_iterations_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score_1 = numeric()
)
# First iteration
# Loop through each unique gymnast
for (i in 1:nrow(unique_gymnasts)) {
  # Extract the current gymnast's information
  current_gymnast <- unique_gymnasts[i, ]
  
  # Subset the data for the current gymnast
  subset_data <- sampling_usa_data_2022_2023_f[sampling_usa_data_2022_2023_f$FirstName == current_gymnast$FirstName & 
                                sampling_usa_data_2022_2023_f$LastName == current_gymnast$LastName, ]
  
  # Sample scores for each apparatus
  VT_subset_data <- subset_data[subset_data$Apparatus == "VT",]
  if (nrow(VT_subset_data) == 0) {
  # If the subset is empty, set the sampled value to 0
    sampled_VT_score <- 0
  } 
  else {
    # If the subset is not empty, sample the "Score" column
    sampled_VT_score <- sample(VT_subset_data$Score, size = 1)
  }
  
  # Create a data frame for the current gymnast's sampled scores and overall score
  current_data <- data.frame(
    FirstName = current_gymnast$FirstName,
    LastName = current_gymnast$LastName,
    Score_1 = sampled_VT_score,
    stringsAsFactors = FALSE
  )
  
  # Append the current data to the overall sampled_scores_data dataframe
  sampled_scores_data <- rbind(sampled_scores_data, current_data)
}

n_iterations_data = sampled_scores_data
#sampled_scores_data = sampled_scores_data[order(-sampled_scores_data$Score), ]

# View the dataframe with sampled scores and overall scores
#print(sampled_scores_data)

for(n in 2:nsimulation){
  sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric())
  for (i in 1:nrow(unique_gymnasts)) {
    # Extract the current gymnast's information
    current_gymnast <- unique_gymnasts[i, ]
    
    # Subset the data for the current gymnast
    subset_data <- sampling_usa_data_2022_2023_f[sampling_usa_data_2022_2023_f$FirstName == current_gymnast$FirstName & 
                                  sampling_usa_data_2022_2023_f$LastName == current_gymnast$LastName, ]
    
    # Sample scores for each apparatus
    VT_subset_data <- subset_data[subset_data$Apparatus == "VT",]
    if (nrow(VT_subset_data) == 0) {
    # If the subset is empty, set the sampled value to 0
      sampled_VT_score <- 0
    } 
    else {
      # If the subset is not empty, sample the "Score" column
      sampled_VT_score <- sample(VT_subset_data$Score, size = 1)
    }
    
    # Create a data frame for the current gymnast's sampled scores and overall score
    current_data <- data.frame(
      FirstName = current_gymnast$FirstName,
      LastName = current_gymnast$LastName,
      Score = sampled_VT_score,
      stringsAsFactors = FALSE
    )
    
    # Append the current data to the overall sampled_scores_data dataframe
    sampled_scores_data <- rbind(sampled_scores_data, current_data)
  }
  n_iterations_data <- cbind(n_iterations_data, sampled_scores_data$Score)
  colnames(n_iterations_data)[colnames(n_iterations_data) == "sampled_scores_data$Score"] <- paste("Score_", n, sep = "")
}

columns_to_average <- n_iterations_data[, -(1:2)]

# Calculate the row-wise mean for the selected columns
n_iterations_data$AverageScore <- rowMeans(columns_to_average, na.rm = TRUE)

final_average_df <- n_iterations_data[, c(1, 2, ncol(n_iterations_data))]

final_average_df = final_average_df[order(-final_average_df$AverageScore), ]
print(final_average_df)
overall_VT_women <- final_average_df
```

```{r UB simulation women, eval = FALSE}
set.seed(123)

# Identify unique gymnasts
unique_gymnasts <- unique(sampling_usa_data_2022_2023_f[, c("FirstName", "LastName")])

# Create a new dataframe to store sampled scores and overall scores
sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric()
)

n_iterations_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score_1 = numeric()
)
# First iteration
# Loop through each unique gymnast
for (i in 1:nrow(unique_gymnasts)) {
  # Extract the current gymnast's information
  current_gymnast <- unique_gymnasts[i, ]
  
  # Subset the data for the current gymnast
  subset_data <- sampling_usa_data_2022_2023_f[sampling_usa_data_2022_2023_f$FirstName == current_gymnast$FirstName & 
                                sampling_usa_data_2022_2023_f$LastName == current_gymnast$LastName, ]
  
  # Sample scores for each apparatus
  UB_subset_data <- subset_data[subset_data$Apparatus == "UB",]
  if (nrow(UB_subset_data) == 0) {
  # If the subset is empty, set the sampled value to 0
    sampled_UB_score <- 0
  } 
  else {
    # If the subset is not empty, sample the "Score" column
    sampled_UB_score <- sample(UB_subset_data$Score, size = 1)
  }
  
  # Create a data frame for the current gymnast's sampled scores and overall score
  current_data <- data.frame(
    FirstName = current_gymnast$FirstName,
    LastName = current_gymnast$LastName,
    Score_1 = sampled_UB_score,
    stringsAsFactors = FALSE
  )
  
  # Append the current data to the overall sampled_scores_data dataframe
  sampled_scores_data <- rbind(sampled_scores_data, current_data)
}

n_iterations_data = sampled_scores_data
#sampled_scores_data = sampled_scores_data[order(-sampled_scores_data$Score), ]

# View the dataframe with sampled scores and overall scores
#print(sampled_scores_data)

for(n in 2:nsimulation){
  sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric())
  for (i in 1:nrow(unique_gymnasts)) {
    # Extract the current gymnast's information
    current_gymnast <- unique_gymnasts[i, ]
    
    # Subset the data for the current gymnast
    subset_data <- sampling_usa_data_2022_2023_f[sampling_usa_data_2022_2023_f$FirstName == current_gymnast$FirstName & 
                                  sampling_usa_data_2022_2023_f$LastName == current_gymnast$LastName, ]
    
    # Sample scores for each apparatus
    UB_subset_data <- subset_data[subset_data$Apparatus == "UB",]
    if (nrow(UB_subset_data) == 0) {
    # If the subset is empty, set the sampled value to 0
      sampled_UB_score <- 0
    } 
    else {
      # If the subset is not empty, sample the "Score" column
      sampled_UB_score <- sample(UB_subset_data$Score, size = 1)
    }
    
    # Create a data frame for the current gymnast's sampled scores and overall score
    current_data <- data.frame(
      FirstName = current_gymnast$FirstName,
      LastName = current_gymnast$LastName,
      Score = sampled_UB_score,
      stringsAsFactors = FALSE
    )
    
    # Append the current data to the overall sampled_scores_data dataframe
    sampled_scores_data <- rbind(sampled_scores_data, current_data)
  }
  n_iterations_data <- cbind(n_iterations_data, sampled_scores_data$Score)
  colnames(n_iterations_data)[colnames(n_iterations_data) == "sampled_scores_data$Score"] <- paste("Score_", n, sep = "")
}

columns_to_average <- n_iterations_data[, -(1:2)]

# Calculate the row-wise mean for the selected columns
n_iterations_data$AverageScore <- rowMeans(columns_to_average, na.rm = TRUE)

final_average_df <- n_iterations_data[, c(1, 2, ncol(n_iterations_data))]

final_average_df = final_average_df[order(-final_average_df$AverageScore), ]
print(final_average_df)
overall_UB_women <- final_average_df
```

```{r overall simulation men, eval = FALSE}
set.seed(123)

# Identify unique gymnasts
unique_gymnasts <- unique(sampling_usa_data_2022_2023_m[, c("FirstName", "LastName")])

# Create a new dataframe to store sampled scores and overall scores
sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric()
)

n_iterations_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score_1 = numeric()
)
# First iteration
# Loop through each unique gymnast
for (i in 1:nrow(unique_gymnasts)) {
  # Extract the current gymnast's information
  current_gymnast <- unique_gymnasts[i, ]
  
  # Subset the data for the current gymnast
  subset_data <- sampling_usa_data_2022_2023_m[sampling_usa_data_2022_2023_m$FirstName == current_gymnast$FirstName & 
                                sampling_usa_data_2022_2023_m$LastName == current_gymnast$LastName, ]
  
  # Sample scores for each apparatus
  HB_subset_data <- subset_data[subset_data$Apparatus == "HB",]
  if (nrow(HB_subset_data) == 0) {
  # If the subset is empty, set the sampled value to 0
    sampled_HB_score <- 0
  } 
  else {
    # If the subset is not empty, sample the "Score" column
    sampled_HB_score <- sample(HB_subset_data$Score, size = 1)
  }
  PB_subset_data <- subset_data[subset_data$Apparatus == "PB",]
  if (nrow(PB_subset_data) == 0) {
  # If the subset is empty, set the sampled value to 0
    sampled_PB_score <- 0
  } 
  else {
    # If the subset is not empty, sample the "Score" column
    sampled_PB_score <- sample(PB_subset_data$Score, size = 1)
  }
  FX_subset_data <- subset_data[subset_data$Apparatus == "FX",]
  if (nrow(FX_subset_data) == 0) {
  # If the subset is empty, set the sampled value to 0
    sampled_FX_score <- 0
  } 
  else {
    # If the subset is not empty, sample the "Score" column
    sampled_FX_score <- sample(FX_subset_data$Score, size = 1)
  }
  VT_subset_data <- subset_data[subset_data$Apparatus == "VT",]
  if (nrow(VT_subset_data) == 0) {
  # If the subset is empty, set the sampled value to 0
    sampled_VT_score <- 0
  } 
  else {
    # If the subset is not empty, sample the "Score" column
    sampled_VT_score <- sample(VT_subset_data$Score, size = 1)
  }
  PH_subset_data <- subset_data[subset_data$Apparatus == "PH",]
  if (nrow(PH_subset_data) == 0) {
  # If the subset is empty, set the sampled value to 0
    sampled_PH_score <- 0
  } 
  else {
    # If the subset is not empty, sample the "Score" column
    sampled_PH_score <- sample(PH_subset_data$Score, size = 1)
  }
  
  SR_subset_data <- subset_data[subset_data$Apparatus == "SR",]
  if (nrow(SR_subset_data) == 0) {
  # If the subset is empty, set the sampled value to 0
    sampled_SR_score <- 0
  } 
  else {
    # If the subset is not empty, sample the "Score" column
    sampled_SR_score <- sample(SR_subset_data$Score, size = 1)
  }
  
  # Calculate overall score
  overall_score <- sampled_HB_score +  sampled_PB_score + sampled_FX_score + sampled_VT_score + sampled_PH_score +  sampled_SR_score
  
  # Create a data frame for the current gymnast's sampled scores and overall score
  current_data <- data.frame(
    FirstName = current_gymnast$FirstName,
    LastName = current_gymnast$LastName,
    Score_1 = overall_score,
    stringsAsFactors = FALSE
  )
  
  # Append the current data to the overall sampled_scores_data dataframe
  sampled_scores_data <- rbind(sampled_scores_data, current_data)
}

n_iterations_data = sampled_scores_data
#sampled_scores_data = sampled_scores_data[order(-sampled_scores_data$Score), ]

# View the dataframe with sampled scores and overall scores
#print(sampled_scores_data)

for(n in 2:nsimulation){
  sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric())
  for (i in 1:nrow(unique_gymnasts)) {
    # Extract the current gymnast's information
    current_gymnast <- unique_gymnasts[i, ]
    
    # Subset the data for the current gymnast
    subset_data <- sampling_usa_data_2022_2023_m[sampling_usa_data_2022_2023_m$FirstName == current_gymnast$FirstName & 
                                sampling_usa_data_2022_2023_m$LastName == current_gymnast$LastName, ]
    
    # Sample scores for each apparatus
    HB_subset_data <- subset_data[subset_data$Apparatus == "HB",]
    if (nrow(HB_subset_data) == 0) {
    # If the subset is empty, set the sampled value to 0
      sampled_HB_score <- 0
    } 
    else {
      # If the subset is not empty, sample the "Score" column
      sampled_HB_score <- sample(HB_subset_data$Score, size = 1)
    }
    PB_subset_data <- subset_data[subset_data$Apparatus == "PB",]
    if (nrow(PB_subset_data) == 0) {
    # If the subset is empty, set the sampled value to 0
      sampled_PB_score <- 0
    } 
    else {
      # If the subset is not empty, sample the "Score" column
      sampled_PB_score <- sample(PB_subset_data$Score, size = 1)
    }
    FX_subset_data <- subset_data[subset_data$Apparatus == "FX",]
    if (nrow(FX_subset_data) == 0) {
    # If the subset is empty, set the sampled value to 0
      sampled_FX_score <- 0
    } 
    else {
      # If the subset is not empty, sample the "Score" column
      sampled_FX_score <- sample(FX_subset_data$Score, size = 1)
    }
    VT_subset_data <- subset_data[subset_data$Apparatus == "VT",]
    if (nrow(VT_subset_data) == 0) {
    # If the subset is empty, set the sampled value to 0
      sampled_VT_score <- 0
    } 
    else {
      # If the subset is not empty, sample the "Score" column
      sampled_VT_score <- sample(VT_subset_data$Score, size = 1)
    }
    PH_subset_data <- subset_data[subset_data$Apparatus == "PH",]
    if (nrow(PH_subset_data) == 0) {
    # If the subset is empty, set the sampled value to 0
      sampled_PH_score <- 0
    } 
    else {
      # If the subset is not empty, sample the "Score" column
      sampled_PH_score <- sample(PH_subset_data$Score, size = 1)
    }
    
    SR_subset_data <- subset_data[subset_data$Apparatus == "SR",]
    if (nrow(SR_subset_data) == 0) {
    # If the subset is empty, set the sampled value to 0
      sampled_SR_score <- 0
    } 
    else {
      # If the subset is not empty, sample the "Score" column
      sampled_SR_score <- sample(SR_subset_data$Score, size = 1)
    }
    
    # Calculate overall score
    overall_score <- sampled_HB_score +  sampled_PB_score + sampled_FX_score + sampled_VT_score + sampled_PH_score +  sampled_SR_score
    
    # Create a data frame for the current gymnast's sampled scores and overall score
    current_data <- data.frame(
      FirstName = current_gymnast$FirstName,
      LastName = current_gymnast$LastName,
      Score = overall_score,
      stringsAsFactors = FALSE
    )
    
    # Append the current data to the overall sampled_scores_data dataframe
    sampled_scores_data <- rbind(sampled_scores_data, current_data)
  }
  n_iterations_data <- cbind(n_iterations_data, sampled_scores_data$Score)
  colnames(n_iterations_data)[colnames(n_iterations_data) == "sampled_scores_data$Score"] <- paste("Score_", n, sep = "")
}

columns_to_average <- n_iterations_data[, -(1:2)]

# Calculate the row-wise mean for the selected columns
n_iterations_data$AverageScore <- rowMeans(columns_to_average, na.rm = TRUE)

final_average_df <- n_iterations_data[, c(1, 2, ncol(n_iterations_data))]

final_average_df = final_average_df[order(-final_average_df$AverageScore), ]
print(final_average_df)
overall_men <- final_average_df
```

```{r HB simulation men, eval = FALSE}
set.seed(123)

# Identify unique gymnasts
unique_gymnasts <- unique(sampling_usa_data_2022_2023_m[, c("FirstName", "LastName")])

# Create a new dataframe to store sampled scores and overall scores
sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric()
)

n_iterations_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score_1 = numeric()
)
# First iteration
# Loop through each unique gymnast
for (i in 1:nrow(unique_gymnasts)) {
  # Extract the current gymnast's information
  current_gymnast <- unique_gymnasts[i, ]
  
  # Subset the data for the current gymnast
  subset_data <- sampling_usa_data_2022_2023_m[sampling_usa_data_2022_2023_m$FirstName == current_gymnast$FirstName & 
                                sampling_usa_data_2022_2023_m$LastName == current_gymnast$LastName, ]
  
  # Sample scores for each apparatus
  HB_subset_data <- subset_data[subset_data$Apparatus == "HB",]
  if (nrow(HB_subset_data) == 0) {
  # If the subset is empty, set the sampled value to 0
    sampled_HB_score <- 0
  } 
  else {
    # If the subset is not empty, sample the "Score" column
    sampled_HB_score <- sample(HB_subset_data$Score, size = 1)
  }
  
  # Create a data frame for the current gymnast's sampled scores and overall score
  current_data <- data.frame(
    FirstName = current_gymnast$FirstName,
    LastName = current_gymnast$LastName,
    Score_1 = sampled_HB_score,
    stringsAsFactors = FALSE
  )
  
  # Append the current data to the overall sampled_scores_data dataframe
  sampled_scores_data <- rbind(sampled_scores_data, current_data)
}

n_iterations_data = sampled_scores_data
#sampled_scores_data = sampled_scores_data[order(-sampled_scores_data$Score), ]

# View the dataframe with sampled scores and overall scores
#print(sampled_scores_data)

for(n in 2:nsimulation){
  sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric())
  for (i in 1:nrow(unique_gymnasts)) {
    # Extract the current gymnast's information
    current_gymnast <- unique_gymnasts[i, ]
    
    # Subset the data for the current gymnast
    subset_data <- sampling_usa_data_2022_2023_m[sampling_usa_data_2022_2023_m$FirstName == current_gymnast$FirstName & 
                                sampling_usa_data_2022_2023_m$LastName == current_gymnast$LastName, ]
    
    # Sample scores for each apparatus
    HB_subset_data <- subset_data[subset_data$Apparatus == "HB",]
    if (nrow(HB_subset_data) == 0) {
    # If the subset is empty, set the sampled value to 0
      sampled_HB_score <- 0
    } 
    else {
      # If the subset is not empty, sample the "Score" column
      sampled_HB_score <- sample(HB_subset_data$Score, size = 1)
    }
    
    # Create a data frame for the current gymnast's sampled scores and overall score
    current_data <- data.frame(
      FirstName = current_gymnast$FirstName,
      LastName = current_gymnast$LastName,
      Score = sampled_HB_score,
      stringsAsFactors = FALSE
    )
    
    # Append the current data to the overall sampled_scores_data dataframe
    sampled_scores_data <- rbind(sampled_scores_data, current_data)
  }
  n_iterations_data <- cbind(n_iterations_data, sampled_scores_data$Score)
  colnames(n_iterations_data)[colnames(n_iterations_data) == "sampled_scores_data$Score"] <- paste("Score_", n, sep = "")
}

columns_to_average <- n_iterations_data[, -(1:2)]

# Calculate the row-wise mean for the selected columns
n_iterations_data$AverageScore <- rowMeans(columns_to_average, na.rm = TRUE)

final_average_df <- n_iterations_data[, c(1, 2, ncol(n_iterations_data))]

final_average_df = final_average_df[order(-final_average_df$AverageScore), ]
print(final_average_df)
overall_HB_men <- final_average_df
```

```{r PB simulation men, eval = FALSE}
set.seed(123)

# Identify unique gymnasts
unique_gymnasts <- unique(sampling_usa_data_2022_2023_m[, c("FirstName", "LastName")])

# Create a new dataframe to store sampled scores and overall scores
sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric()
)

n_iterations_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score_1 = numeric()
)
# First iteration
# Loop through each unique gymnast
for (i in 1:nrow(unique_gymnasts)) {
  # Extract the current gymnast's information
  current_gymnast <- unique_gymnasts[i, ]
  
  # Subset the data for the current gymnast
  subset_data <- sampling_usa_data_2022_2023_m[sampling_usa_data_2022_2023_m$FirstName == current_gymnast$FirstName & 
                                sampling_usa_data_2022_2023_m$LastName == current_gymnast$LastName, ]
  
  # Sample scores for each apparatus
  PB_subset_data <- subset_data[subset_data$Apparatus == "PB",]
  if (nrow(PB_subset_data) == 0) {
  # If the subset is empty, set the sampled value to 0
    sampled_PB_score <- 0
  } 
  else {
    # If the subset is not empty, sample the "Score" column
    sampled_PB_score <- sample(PB_subset_data$Score, size = 1)
  }
  
  # Create a data frame for the current gymnast's sampled scores and overall score
  current_data <- data.frame(
    FirstName = current_gymnast$FirstName,
    LastName = current_gymnast$LastName,
    Score_1 = sampled_PB_score,
    stringsAsFactors = FALSE
  )
  
  # Append the current data to the overall sampled_scores_data dataframe
  sampled_scores_data <- rbind(sampled_scores_data, current_data)
}

n_iterations_data = sampled_scores_data
#sampled_scores_data = sampled_scores_data[order(-sampled_scores_data$Score), ]

# View the dataframe with sampled scores and overall scores
#print(sampled_scores_data)

for(n in 2:nsimulation){
  sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric())
  for (i in 1:nrow(unique_gymnasts)) {
    # Extract the current gymnast's information
    current_gymnast <- unique_gymnasts[i, ]
    
    # Subset the data for the current gymnast
    subset_data <- sampling_usa_data_2022_2023_m[sampling_usa_data_2022_2023_m$FirstName == current_gymnast$FirstName & 
                                sampling_usa_data_2022_2023_m$LastName == current_gymnast$LastName, ]
    
    # Sample scores for each apparatus
    PB_subset_data <- subset_data[subset_data$Apparatus == "PB",]
    if (nrow(PB_subset_data) == 0) {
    # If the subset is empty, set the sampled value to 0
      sampled_PB_score <- 0
    } 
    else {
      # If the subset is not empty, sample the "Score" column
      sampled_PB_score <- sample(PB_subset_data$Score, size = 1)
    }
    
    # Create a data frame for the current gymnast's sampled scores and overall score
    current_data <- data.frame(
      FirstName = current_gymnast$FirstName,
      LastName = current_gymnast$LastName,
      Score = sampled_PB_score,
      stringsAsFactors = FALSE
    )
    
    # Append the current data to the overall sampled_scores_data dataframe
    sampled_scores_data <- rbind(sampled_scores_data, current_data)
  }
  n_iterations_data <- cbind(n_iterations_data, sampled_scores_data$Score)
  colnames(n_iterations_data)[colnames(n_iterations_data) == "sampled_scores_data$Score"] <- paste("Score_", n, sep = "")
}

columns_to_average <- n_iterations_data[, -(1:2)]

# Calculate the row-wise mean for the selected columns
n_iterations_data$AverageScore <- rowMeans(columns_to_average, na.rm = TRUE)

final_average_df <- n_iterations_data[, c(1, 2, ncol(n_iterations_data))]

final_average_df = final_average_df[order(-final_average_df$AverageScore), ]
print(final_average_df)
overall_PB_men <- final_average_df
```

```{r PH simulation men, eval = FALSE}
set.seed(123)

# Identify unique gymnasts
unique_gymnasts <- unique(sampling_usa_data_2022_2023_m[, c("FirstName", "LastName")])

# Create a new dataframe to store sampled scores and overall scores
sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric()
)

n_iterations_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score_1 = numeric()
)
# First iteration
# Loop through each unique gymnast
for (i in 1:nrow(unique_gymnasts)) {
  # Extract the current gymnast's information
  current_gymnast <- unique_gymnasts[i, ]
  
  # Subset the data for the current gymnast
  subset_data <- sampling_usa_data_2022_2023_m[sampling_usa_data_2022_2023_m$FirstName == current_gymnast$FirstName & 
                                sampling_usa_data_2022_2023_m$LastName == current_gymnast$LastName, ]
  
  # Sample scores for each apparatus
  PH_subset_data <- subset_data[subset_data$Apparatus == "PH",]
  if (nrow(PH_subset_data) == 0) {
  # If the subset is empty, set the sampled value to 0
    sampled_PH_score <- 0
  } 
  else {
    # If the subset is not empty, sample the "Score" column
    sampled_PH_score <- sample(PH_subset_data$Score, size = 1)
  }
  
  # Create a data frame for the current gymnast's sampled scores and overall score
  current_data <- data.frame(
    FirstName = current_gymnast$FirstName,
    LastName = current_gymnast$LastName,
    Score_1 = sampled_PH_score,
    stringsAsFactors = FALSE
  )
  
  # Append the current data to the overall sampled_scores_data dataframe
  sampled_scores_data <- rbind(sampled_scores_data, current_data)
}

n_iterations_data = sampled_scores_data
#sampled_scores_data = sampled_scores_data[order(-sampled_scores_data$Score), ]

# View the dataframe with sampled scores and overall scores
#print(sampled_scores_data)

for(n in 2:nsimulation){
  sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric())
  for (i in 1:nrow(unique_gymnasts)) {
    # Extract the current gymnast's information
    current_gymnast <- unique_gymnasts[i, ]
    
    # Subset the data for the current gymnast
    subset_data <- sampling_usa_data_2022_2023_m[sampling_usa_data_2022_2023_m$FirstName == current_gymnast$FirstName & 
                                sampling_usa_data_2022_2023_m$LastName == current_gymnast$LastName, ]
    
    # Sample scores for each apparatus
    PH_subset_data <- subset_data[subset_data$Apparatus == "PH",]
    if (nrow(PH_subset_data) == 0) {
    # If the subset is empty, set the sampled value to 0
      sampled_PH_score <- 0
    } 
    else {
      # If the subset is not empty, sample the "Score" column
      sampled_PH_score <- sample(PH_subset_data$Score, size = 1)
    }
    
    # Create a data frame for the current gymnast's sampled scores and overall score
    current_data <- data.frame(
      FirstName = current_gymnast$FirstName,
      LastName = current_gymnast$LastName,
      Score = sampled_PH_score,
      stringsAsFactors = FALSE
    )
    
    # Append the current data to the overall sampled_scores_data dataframe
    sampled_scores_data <- rbind(sampled_scores_data, current_data)
  }
  n_iterations_data <- cbind(n_iterations_data, sampled_scores_data$Score)
  colnames(n_iterations_data)[colnames(n_iterations_data) == "sampled_scores_data$Score"] <- paste("Score_", n, sep = "")
}

columns_to_average <- n_iterations_data[, -(1:2)]

# Calculate the row-wise mean for the selected columns
n_iterations_data$AverageScore <- rowMeans(columns_to_average, na.rm = TRUE)

final_average_df <- n_iterations_data[, c(1, 2, ncol(n_iterations_data))]

final_average_df = final_average_df[order(-final_average_df$AverageScore), ]
print(final_average_df)
overall_PH_men <- final_average_df
```

```{r FX simulation men, eval = FALSE}
set.seed(123)

# Identify unique gymnasts
unique_gymnasts <- unique(sampling_usa_data_2022_2023_m[, c("FirstName", "LastName")])

# Create a new dataframe to store sampled scores and overall scores
sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric()
)

n_iterations_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score_1 = numeric()
)
# First iteration
# Loop through each unique gymnast
for (i in 1:nrow(unique_gymnasts)) {
  # Extract the current gymnast's information
  current_gymnast <- unique_gymnasts[i, ]
  
  # Subset the data for the current gymnast
  subset_data <- sampling_usa_data_2022_2023_m[sampling_usa_data_2022_2023_m$FirstName == current_gymnast$FirstName & 
                                sampling_usa_data_2022_2023_m$LastName == current_gymnast$LastName, ]
  
  # Sample scores for each apparatus
  FX_subset_data <- subset_data[subset_data$Apparatus == "FX",]
  if (nrow(FX_subset_data) == 0) {
  # If the subset is empty, set the sampled value to 0
    sampled_FX_score <- 0
  } 
  else {
    # If the subset is not empty, sample the "Score" column
    sampled_FX_score <- sample(FX_subset_data$Score, size = 1)
  }
  
  # Create a data frame for the current gymnast's sampled scores and overall score
  current_data <- data.frame(
    FirstName = current_gymnast$FirstName,
    LastName = current_gymnast$LastName,
    Score_1 = sampled_FX_score,
    stringsAsFactors = FALSE
  )
  
  # Append the current data to the overall sampled_scores_data dataframe
  sampled_scores_data <- rbind(sampled_scores_data, current_data)
}

n_iterations_data = sampled_scores_data
#sampled_scores_data = sampled_scores_data[order(-sampled_scores_data$Score), ]

# View the dataframe with sampled scores and overall scores
#print(sampled_scores_data)

for(n in 2:nsimulation){
  sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric())
  for (i in 1:nrow(unique_gymnasts)) {
    # Extract the current gymnast's information
    current_gymnast <- unique_gymnasts[i, ]
    
    # Subset the data for the current gymnast
    subset_data <- sampling_usa_data_2022_2023_m[sampling_usa_data_2022_2023_m$FirstName == current_gymnast$FirstName & 
                                sampling_usa_data_2022_2023_m$LastName == current_gymnast$LastName, ]
    
    # Sample scores for each apparatus
    FX_subset_data <- subset_data[subset_data$Apparatus == "FX",]
    if (nrow(FX_subset_data) == 0) {
    # If the subset is empty, set the sampled value to 0
      sampled_FX_score <- 0
    } 
    else {
      # If the subset is not empty, sample the "Score" column
      sampled_FX_score <- sample(FX_subset_data$Score, size = 1)
    }
    
    # Create a data frame for the current gymnast's sampled scores and overall score
    current_data <- data.frame(
      FirstName = current_gymnast$FirstName,
      LastName = current_gymnast$LastName,
      Score = sampled_FX_score,
      stringsAsFactors = FALSE
    )
    
    # Append the current data to the overall sampled_scores_data dataframe
    sampled_scores_data <- rbind(sampled_scores_data, current_data)
  }
  n_iterations_data <- cbind(n_iterations_data, sampled_scores_data$Score)
  colnames(n_iterations_data)[colnames(n_iterations_data) == "sampled_scores_data$Score"] <- paste("Score_", n, sep = "")
}

columns_to_average <- n_iterations_data[, -(1:2)]

# Calculate the row-wise mean for the selected columns
n_iterations_data$AverageScore <- rowMeans(columns_to_average, na.rm = TRUE)

final_average_df <- n_iterations_data[, c(1, 2, ncol(n_iterations_data))]

final_average_df = final_average_df[order(-final_average_df$AverageScore), ]
print(final_average_df)
overall_FX_men <- final_average_df
```

```{r VT simulation men, eval = FALSE}
set.seed(123)

# Identify unique gymnasts
unique_gymnasts <- unique(sampling_usa_data_2022_2023_m[, c("FirstName", "LastName")])

# Create a new dataframe to store sampled scores and overall scores
sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric()
)

n_iterations_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score_1 = numeric()
)
# First iteration
# Loop through each unique gymnast
for (i in 1:nrow(unique_gymnasts)) {
  # Extract the current gymnast's information
  current_gymnast <- unique_gymnasts[i, ]
  
  # Subset the data for the current gymnast
  subset_data <- sampling_usa_data_2022_2023_m[sampling_usa_data_2022_2023_m$FirstName == current_gymnast$FirstName & 
                                sampling_usa_data_2022_2023_m$LastName == current_gymnast$LastName, ]
  
  # Sample scores for each apparatus
  VT_subset_data <- subset_data[subset_data$Apparatus == "VT",]
  if (nrow(VT_subset_data) == 0) {
  # If the subset is empty, set the sampled value to 0
    sampled_VT_score <- 0
  } 
  else {
    # If the subset is not empty, sample the "Score" column
    sampled_VT_score <- sample(VT_subset_data$Score, size = 1)
  }
  
  # Create a data frame for the current gymnast's sampled scores and overall score
  current_data <- data.frame(
    FirstName = current_gymnast$FirstName,
    LastName = current_gymnast$LastName,
    Score_1 = sampled_VT_score,
    stringsAsFactors = FALSE
  )
  
  # Append the current data to the overall sampled_scores_data dataframe
  sampled_scores_data <- rbind(sampled_scores_data, current_data)
}

n_iterations_data = sampled_scores_data
#sampled_scores_data = sampled_scores_data[order(-sampled_scores_data$Score), ]

# View the dataframe with sampled scores and overall scores
#print(sampled_scores_data)

for(n in 2:nsimulation){
  sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric())
  for (i in 1:nrow(unique_gymnasts)) {
    # Extract the current gymnast's information
    current_gymnast <- unique_gymnasts[i, ]
    
    # Subset the data for the current gymnast
    subset_data <- sampling_usa_data_2022_2023_m[sampling_usa_data_2022_2023_m$FirstName == current_gymnast$FirstName & 
                                sampling_usa_data_2022_2023_m$LastName == current_gymnast$LastName, ]
    
    # Sample scores for each apparatus
    VT_subset_data <- subset_data[subset_data$Apparatus == "VT",]
    if (nrow(VT_subset_data) == 0) {
    # If the subset is empty, set the sampled value to 0
      sampled_VT_score <- 0
    } 
    else {
      # If the subset is not empty, sample the "Score" column
      sampled_VT_score <- sample(VT_subset_data$Score, size = 1)
    }
    
    # Create a data frame for the current gymnast's sampled scores and overall score
    current_data <- data.frame(
      FirstName = current_gymnast$FirstName,
      LastName = current_gymnast$LastName,
      Score = sampled_VT_score,
      stringsAsFactors = FALSE
    )
    
    # Append the current data to the overall sampled_scores_data dataframe
    sampled_scores_data <- rbind(sampled_scores_data, current_data)
  }
  n_iterations_data <- cbind(n_iterations_data, sampled_scores_data$Score)
  colnames(n_iterations_data)[colnames(n_iterations_data) == "sampled_scores_data$Score"] <- paste("Score_", n, sep = "")
}

columns_to_average <- n_iterations_data[, -(1:2)]

# Calculate the row-wise mean for the selected columns
n_iterations_data$AverageScore <- rowMeans(columns_to_average, na.rm = TRUE)

final_average_df <- n_iterations_data[, c(1, 2, ncol(n_iterations_data))]

final_average_df = final_average_df[order(-final_average_df$AverageScore), ]
print(final_average_df)
overall_VT_men <- final_average_df
```

```{r SR simulation men, eval = FALSE}
set.seed(123)

# Identify unique gymnasts
unique_gymnasts <- unique(sampling_usa_data_2022_2023_m[, c("FirstName", "LastName")])

# Create a new dataframe to store sampled scores and overall scores
sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric()
)

n_iterations_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score_1 = numeric()
)
# First iteration
# Loop through each unique gymnast
for (i in 1:nrow(unique_gymnasts)) {
  # Extract the current gymnast's information
  current_gymnast <- unique_gymnasts[i, ]
  
  # Subset the data for the current gymnast
  subset_data <- sampling_usa_data_2022_2023_m[sampling_usa_data_2022_2023_m$FirstName == current_gymnast$FirstName & 
                                sampling_usa_data_2022_2023_m$LastName == current_gymnast$LastName, ]
  
  # Sample scores for each apparatus
  SR_subset_data <- subset_data[subset_data$Apparatus == "SR",]
  if (nrow(SR_subset_data) == 0) {
  # If the subset is empty, set the sampled value to 0
    sampled_SR_score <- 0
  } 
  else {
    # If the subset is not empty, sample the "Score" column
    sampled_SR_score <- sample(SR_subset_data$Score, size = 1)
  }
  
  # Create a data frame for the current gymnast's sampled scores and overall score
  current_data <- data.frame(
    FirstName = current_gymnast$FirstName,
    LastName = current_gymnast$LastName,
    Score_1 = sampled_SR_score,
    stringsAsFactors = FALSE
  )
  
  # Append the current data to the overall sampled_scores_data dataframe
  sampled_scores_data <- rbind(sampled_scores_data, current_data)
}

n_iterations_data = sampled_scores_data
#sampled_scores_data = sampled_scores_data[order(-sampled_scores_data$Score), ]

# View the dataframe with sampled scores and overall scores
#print(sampled_scores_data)

for(n in 2:nsimulation){
  sampled_scores_data <- data.frame(
  FirstName = character(),
  LastName = character(),
  Score = numeric())
  for (i in 1:nrow(unique_gymnasts)) {
    # Extract the current gymnast's information
    current_gymnast <- unique_gymnasts[i, ]
    
    # Subset the data for the current gymnast
    subset_data <- sampling_usa_data_2022_2023_m[sampling_usa_data_2022_2023_m$FirstName == current_gymnast$FirstName & 
                                sampling_usa_data_2022_2023_m$LastName == current_gymnast$LastName, ]
    
    # Sample scores for each apparatus
    SR_subset_data <- subset_data[subset_data$Apparatus == "SR",]
    if (nrow(SR_subset_data) == 0) {
    # If the subset is empty, set the sampled value to 0
      sampled_SR_score <- 0
    } 
    else {
      # If the subset is not empty, sample the "Score" column
      sampled_SR_score <- sample(SR_subset_data$Score, size = 1)
    }
    
    # Create a data frame for the current gymnast's sampled scores and overall score
    current_data <- data.frame(
      FirstName = current_gymnast$FirstName,
      LastName = current_gymnast$LastName,
      Score = sampled_SR_score,
      stringsAsFactors = FALSE
    )
    
    # Append the current data to the overall sampled_scores_data dataframe
    sampled_scores_data <- rbind(sampled_scores_data, current_data)
  }
  n_iterations_data <- cbind(n_iterations_data, sampled_scores_data$Score)
  colnames(n_iterations_data)[colnames(n_iterations_data) == "sampled_scores_data$Score"] <- paste("Score_", n, sep = "")
}

columns_to_average <- n_iterations_data[, -(1:2)]

# Calculate the row-wise mean for the selected columns
n_iterations_data$AverageScore <- rowMeans(columns_to_average, na.rm = TRUE)

final_average_df <- n_iterations_data[, c(1, 2, ncol(n_iterations_data))]

final_average_df = final_average_df[order(-final_average_df$AverageScore), ]
print(final_average_df)
overall_SR_men <- final_average_df
```

```{r}
usa_data_2022_2023 <- rbind(usa_data_2022_2023, usa_data_2017_2021)

data_2017_2021 |>
  summarise(mean = mean(Score, na.rm = TRUE))

data_2022_2023 |>
  summarise(mean = mean(Score))

usa_data_2022_2023_f <-  usa_data_2022_2023 |>
  filter(Gender == "w")

usa_data_2022_2023_m <- usa_data_2022_2023 |>
  filter(Gender == "m")

data_2022_2023_f <- data_2022_2023 |>
  filter(Gender == "w")

data_2022_2023_m <- data_2022_2023 |>
  filter(Gender == "m")

ggplot(aes(x= Score), data = usa_data_2022_2023_f) + geom_histogram() + facet_wrap(~Apparatus, scales = "free_y", ncol = 2)

ggplot(aes(x= Score), data = usa_data_2022_2023_m) + geom_histogram() + facet_wrap(~Apparatus, scales = "free_y", ncol = 2)


mean_usa_app <- usa_data_2022_2023_f |>
  group_by(LastName, FirstName, Apparatus) |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score))

mean_usa_app_men <- usa_data_2022_2023_m |>
  group_by(LastName, FirstName, Apparatus) |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score))

usa_data_2022_2023_f_BB <- mean_usa_app |>
  filter(Apparatus == "BB") |>
  arrange(desc(mean_score))

usa_data_2022_2023_f_UB <- mean_usa_app |>
  filter(Apparatus == "UB") |>
  arrange(desc(mean_score))

usa_data_2022_2023_f_FX <- mean_usa_app |>
  filter(Apparatus == "FX") |>
  arrange(desc(mean_score))

usa_data_2022_2023_f_VT <- mean_usa_app |>
  filter(Apparatus == "VT") |>
  arrange(desc(mean_score))

mean_usa_app

mean_usa_app_men

usa_data_2022_2023_f_BB
usa_data_2022_2023_f_UB
usa_data_2022_2023_f_FX
usa_data_2022_2023_f_VT

mean_usa_app |>
  group_by(LastName, FirstName) |>
  filter(Apparatus != "VT1",
         Apparatus != "VT2") |>
  summarise(sum = sum(mean_score)) |>
  arrange(desc(sum))

VT_ranks_f <- data_2022_2023_f |>
  group_by(LastName, FirstName, Country, Apparatus) |>
  filter(Apparatus == "VT") |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score)) |>
  arrange(desc(mean_score)) |>
  head(24)

BB_ranks <- data_2022_2023_f |>
  group_by(LastName, FirstName, Country, Apparatus) |>
  filter(Apparatus == "BB") |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score)) |>
  arrange(desc(mean_score)) |>
  head(24)

UB_ranks <- data_2022_2023_f |>
  group_by(LastName, FirstName, Country, Apparatus) |>
  filter(Apparatus == "UB") |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score)) |>
  arrange(desc(mean_score)) |>
  head(24)

FX_ranks_f <- data_2022_2023_f |>
  group_by(LastName, FirstName, Country, Apparatus) |>
  filter(Apparatus == "FX") |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score)) |>
  arrange(desc(mean_score)) |>
  head(24)

#----------------------------------------------------------

VT_ranks_m <- data_2022_2023_m |>
  group_by(LastName, FirstName, Country, Apparatus) |>
  filter(Apparatus == "VT") |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score)) |>
  arrange(desc(mean_score)) |>
  head(24)

SR_ranks <- data_2022_2023_m |>
  group_by(LastName, FirstName, Country, Apparatus) |>
  filter(Apparatus == "SR") |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score)) |>
  arrange(desc(mean_score)) |>
  head(24)

PB_ranks <- data_2022_2023_m |>
  group_by(LastName, FirstName, Country, Apparatus) |>
  filter(Apparatus == "PB") |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score)) |>
  arrange(desc(mean_score)) |>
  head(24)

FX_ranks_m <- data_2022_2023_m |>
  group_by(LastName, FirstName, Country, Apparatus) |>
  filter(Apparatus == "FX") |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score)) |>
  arrange(desc(mean_score)) |>
  head(24)

PH_ranks <- data_2022_2023_m |>
  group_by(LastName, FirstName, Country, Apparatus) |>
  filter(Apparatus == "PH") |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score)) |>
  arrange(desc(mean_score)) |>
  head(24)

HB_ranks <- data_2022_2023_m |>
  group_by(LastName, FirstName, Country, Apparatus) |>
  filter(Apparatus == "HB") |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score)) |>
  arrange(desc(mean_score)) |>
  head(24)

```

```{r medal-cutoffs}
## sample 24 times from top 24 athletes mean scores in each apparatus to simulate one "olympics"
## take top 3 scores and those are cutoffs for gold/silver/bronze respectively
# Returns data frame with three rows (gold, silver, bronze) and a column for each simulation
getmedalcutoffs <- function(eventranks, num_simulations = 1000) {
  set.seed(123)
  distribution <- eventranks$mean_score
  cutoffs <- matrix(NA, nrow = 3, ncol = num_simulations)

  for (i in 1:num_simulations) {
    top_three_scores = numeric(0)
    while (length(unique(top_three_scores))<3){
    # Sample 24 times from the distribution
    simulated_scores <- sample(distribution, size = 24, replace = TRUE)

    # Take the top 3 scores
    top_three_scores <- head(sort(simulated_scores, decreasing = TRUE), 3)
    }
    # Set the cutoffs for gold, silver, and bronze in the matrix
    cutoffs[, i] <- top_three_scores
  }

  # Convert the matrix to a data frame
  cutoffs_df <- as.data.frame(cutoffs)
  names(cutoffs_df) <- paste0("Simulation_", 1:num_simulations)

  return(cutoffs_df)
}
```

```{r get-cutoffs}
BB_medal_cutoffs <- getmedalcutoffs(BB_ranks)
FX_f_medal_cutoffs <- getmedalcutoffs(FX_ranks_f)
UB_medal_cutoffs <- getmedalcutoffs(UB_ranks)
VT_f_medal_cutoffs <- getmedalcutoffs(VT_ranks_f)

FX_m_medal_cutoffs <- getmedalcutoffs(FX_ranks_m)
SR_medal_cutoffs <- getmedalcutoffs(SR_ranks)
HB_medal_cutoffs <- getmedalcutoffs(HB_ranks)
PH_medal_cutoffs <- getmedalcutoffs(PH_ranks)
VT_m_medal_cutoffs <- getmedalcutoffs(VT_ranks_m)
PB_medal_cutoffs <- getmedalcutoffs(PB_ranks)
```

```{r get-model-probs-func}
calculatePodiumPercentages <- function(df, thresholds) {
  # Number of gymnasts
  num_gymnasts <- nrow(df)
  
  # Initialize an empty dataframe for the results
  results <- data.frame(
    firstName = df[, 1],
    lastName = df[, 2],
    bronze_percentage = numeric(num_gymnasts),
    silver_percentage = numeric(num_gymnasts),
    gold_percentage = numeric(num_gymnasts),
    stringsAsFactors = FALSE
  )
  
  # Iterating over each set of scores
  for (i in 1:1000) {
    # Extract the scores for the ith sample and the thresholds
    sample_scores <- df[, i + 2]
    gold_threshold <- thresholds[1, i]
    silver_threshold <- thresholds[2, i]
    bronze_threshold <- thresholds[3, i]

    # Count placements based on thresholds
    results$gold_percentage <- results$gold_percentage + (sample_scores >= gold_threshold)
    results$silver_percentage <- results$silver_percentage + (sample_scores >= silver_threshold & sample_scores < gold_threshold)
    results$bronze_percentage <- results$bronze_percentage + (sample_scores >= bronze_threshold & sample_scores < silver_threshold)
  }

  # Convert counts to percentages
  results$gold_percentage <- (results$gold_percentage / 1000)
  results$silver_percentage <- (results$silver_percentage / 1000)
  results$bronze_percentage <- (results$bronze_percentage / 1000)

  # Sort the dataframe by gold_percentage in descending order
  results <- results[order(-results$gold_percentage), ]
  
  return(results)
}
```

```{r write-percs-example}
sims_data <- read_csv("Data/HB_usa_mens_sims.csv")
percs <- calculatePodiumPercentages(sims_data, HB_medal_cutoffs)
# write.csv(percs, '/home/guest/Case2-BDSM/Data/event_percentages/m_HB.csv', row.names=FALSE)
```

```{r}
#breakdown of teams qualifying rank

tb_2016_f <- data.frame(rank = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                      country = c("USA", "CHN", "RUS", "GBR", "BRA", "GER", "JPN", "NED", "CAN", "ITA", "FRA", "BEL"),
                      all_around = c(3, 2, 3, 2, 3, 2, 3, 3, 2, 2, 3, 2))

tb_2016_f <- tb_2016_f |>
  mutate(year = "2016",
         made_final = ifelse(rank <= 8, "yes", "no"),
         gender = "F")

tb_2016_m <- data.frame(rank = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                      country = c("CHN", "USA", "RUS", "JPN", "GBR", "BRA", "UKR", "GER", "SUI", "NED", "KOR", "FRA"),
                      all_around = c(2, 2, 3, 2, 3, 3, 2, 2, 3, 3, 1, 2))

tb_2016_m <- tb_2016_m |>
  mutate(year = "2016",
         made_final = ifelse(rank <= 8, "yes", "no"),
         gender = "M")

tb_2012_f <- data.frame(rank = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                      country = c("USA", "RUS", "CHN", "ROU", "GBR", "JPN", "ITA", "CAN", "GER", "AUS", "FRA", "BRA"),
                      all_around = c(3, 3, 3, 2, 3, 2, 3, 2, 2, 2, 2, 3))

tb_2012_f <- tb_2012_f |>
  mutate(year = "2012",
         made_final = ifelse(rank <= 8, "yes", "no"),
         gender = "F")

tb_2012_m <- data.frame(rank = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                      country = c("USA", "RUS", "GBR", "GER", "JPN", "CHN", "UKR", "FRA", "ESP", "ROU", "ITA", "KOR"),
                      all_around = c(2, 2, 2, 3, 3, 1, 3, 1, 3, 1, 3, 1))

tb_2012_m <- tb_2012_m |>
  mutate(year = "2012",
         made_final = ifelse(rank <= 8, "yes", "no"),
         gender = "M")

tb_f <- rbind(tb_2016_f, tb_2012_f) |>
  mutate(all_around = as.character(all_around))

ggplot(data = tb_f, aes(x = all_around, fill = made_final)) +
  geom_bar()

ggplot(data = tb_f, aes(y = all_around, x = rank)) +
  geom_line()

sampling_usa_data_2022_2023_m |>
  filter(Apparatus == 'PH') |>
  ggplot(aes(x=Score)) +
  geom_histogram()
```

```{r}
# write.csv(overall_women, '/Users/christophertsai/Downloads/Competition Dataframes/overall_women.csv', row.names=FALSE)
```

