---
title: "updated"
output: pdf_document
date: "2024-07-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r packages}
library(readr)
library(tidyverse)
library(dplyr)
library(stringr)
library(lubridate)
```
### Cleaning and Data Prep

```{r loadingdata}
# using data from 2017-2024

newdata <- read.csv("gym_data_22_24.csv")
data_2017_2021 <- read_csv("App-1/data/data_2017_2021.csv")
rawdata <- rbind(newdata, data_2017_2021)
```


```{r cleaning function}

data_cleaning <- function(data) {
  #DO NOT CHANGE ORDER
  
  data$Apparatus[data$Apparatus == "VT2"] <- "VT"
  data$Apparatus[data$Apparatus == "VT1"] <- "VT"
  data$Apparatus[data$Apparatus == "UE"] <- "UB"
  
  data$Penalty[is.na(data$Penalty)] <- 0
  
  #Girls filtering for middle name
  data$FirstName[data$FirstName == "Joscelyn Michelle"] <- "Joscelyn"
  data$FirstName[data$FirstName == "Nola Rhianne"] <- "Nola"
  
  #Guys filtering for middle name
  data$FirstName[data$FirstName == "Taylor Troy"] <- "Taylor"
  data$FirstName[data$FirstName == "Joshua Andrew"] <- "Joshua"
  data$FirstName[data$FirstName == "Yul Kyung Tae"] <- "Yul"
  data$FirstName[data$FirstName == "Curran Michael"] <- "Curran"
  data$FirstName[data$FirstName == "Frederick Nathaniel"] <- "Frederick"
  data$FirstName[data$FirstName == "Ian Hunter"] <- "Ian"
  data$FirstName[data$FirstName == "Shane Michael"] <- "Shane"
  data$FirstName[data$FirstName == "Khoi Alexander"] <- "Khoi"
  
  data$FirstName[data$FirstName == "Yunus Emre"] <- "Yunus"
  
  data$FirstName[data$FirstName == "Yuan-Hsi"] <- "Yuan Hsi"
  
  data$FirstName[data$FirstName == "Yu-Jan"] <- "Yu Jan"
  
  data$LastName[data$LastName == "VILLAVERDE MEDEROS"] <- "VILLAVERDE"
  
  data$LastName[data$LastName == "VALENZUELA ASTUDILLO"] <- "VALENZUELA"
  
  data$FirstName[data$FirstName == "Yiseth Eliana"] <- "Yiseth"
  data$FirstName[data$FirstName == "Yi-Chen"] <- "Yi Chen"
  data$FirstName[data$FirstName == "Yi-Chun"] <- "Yi Chun"
  
  data$FirstName[data$FirstName == "Yefferson Gregorio"] <- "Yefferson"
  data$LastName[data$LastName == "ANTON YEGUEZ"] <- "ANTON"
  
  data$LastName[data$LastName == "ANTON YEGUEZ"] <- "ANTON"
  
  data$FirstName[data$FirstName == "Wout Johan Alexander"] <- "Wout"
  
  data$FirstName[data$FirstName == "Wilfry Manuel"] <- "Wilfry"
  
  data$FirstName[data$FirstName == "Wei-Sheng"] <- "Wei Sheng"
  
  data$FirstName[(data$Competition == "BIRMINGHAM 2022 Commonwealth Games") &
                             (is.na(data$LastName))] <- "Kate"
  
  data$LastName[(data$Competition == "BIRMINGHAM 2022 Commonwealth Games") &
                            (is.na(data$LastName))] <- "MCDONALD"
  
  data$FirstName[data$LastName == "SOUZA BITENCOU"] <- "Lucas"
  data$LastName[data$LastName == "SOUZA BITENCOU"] <- "BITENCOURT"
  
  data$LastName[data$LastName == "DE JESUS DOS SANTOS"] <- "JESUS SANTOS"
  
  data$FirstName[data$LastName == "JESUS SANT"] <- "Melanie"
  data$LastName[data$LastName == "JESUS SANT"] <- "JESUS SANTOS"
  
  data$LastName[data$LastName == "ELPITIYA BADALGE DONA"] <- "GEHANI"
  data$FirstName[data$FirstName == "Milka Gehani"] <- "Milka"
  
  data$FirstName[data$LastName == "ELPITIYA BADALG D"] <- "Milka"
  
  data$LastName[data$LastName == "ELPITIYA BADALG D"] <- "GEHANI"
  
  data$FirstName[(data$Competition == "2022 51st FIG Artistic Gymnastics World Championship") &
                             (is.na(data$LastName))] <- "Kate"
  
  data$LastName[(data$Competition == "2022 51st FIG Artistic Gymnastics World Championship") &
                            (is.na(data$LastName))] <- "MCDONALD"
  
  data$FirstName[(data$Competition == "2023 Varna World Challenge Cup") &
                             (is.na(data$LastName))] <- "Daria"
  
  data$LastName[(data$Competition == "2023 Varna World Challenge Cup") &
                            (is.na(data$LastName))] <- "HARTMANN"
  
  data$FirstName[data$LastName == "ABIYURAFI"] <- "Abiyu"
  data$LastName[data$LastName == "ABIYURAFI"] <- "Rafi"
  
  data$FirstName[data$LastName == "Frederick Nathaniel"] <- "Frederick"
  data$FirstName[data$FirstName == "Fred"] <- "FREDERICK"
  data$FirstName[data$FirstName == "Viktoriia"] <- "Viktoria"
  data$LastName[data$LastName == "D AMATO"] <- "D'AMATO"
  
  data <- data %>% mutate(LastName = str_to_title(LastName))
  
  data$Apparatus[data$Apparatus == "VT2"] <- "VT"
  data$Apparatus[data$Apparatus == "VT1"] <- "VT"
  
  # data cleaning
  extract_second_date <- function(date_string) {
  parts <- str_extract_all(date_string, "\\d{1,2}\\s[A-Za-z]+\\s\\d{4}")[[1]]
  if (length(parts) == 2) {
    # If there are two dates, return the second one
    return(parts[2])
  } else if (length(parts) == 1) {
    # If there is only one date, return it
    return(parts[1])
  } else {
    return(NA)
  }
}

# Step 2: Apply the function to the Date column and convert to Date objects
data <- data %>%
  mutate(
    SecondDateStr = sapply(Date, extract_second_date),
    SecondDate = dmy(SecondDateStr)
  )

# Define the end date
end_date <- dmy("27-07-2024")

# Calculate the number of days from the SecondDate to the end date
data <- data %>%
  mutate(
    DaysUntil2024 = as.integer(end_date - SecondDate)
  )
  
  
  
}

```

```{r cleaning}
cleaned_data <- data_cleaning(rawdata)
```

### Simulations

```{r sampling_dist}

create_sampling_dist <- function(data){
  final_rows_full <- data[grep("final|Final", data$Round), ]
  less_than_180_rows <- data[data$DaysUntil2024 < 180, ]
  between_180_540_rows <- data[data$DaysUntil2024 >= 180 &
                                 data$DaysUntil2024 <= 540, ]
  
  sampling_data <- rbind(
    data,
    final_rows_full,
    less_than_180_rows,
    less_than_180_rows,
    between_180_540_rows
  )
  return (sampling_data)


}
sampling_data <- create_sampling_dist(cleaned_data)

usa_mens_roster <- c("Hong", "Juda", "Malone","Nedoroscik", "Richard")
usa_womens_roster <- c("Biles", "Carey", "Chiles", "Lee", "Rivera")

sampling_usa_data_f <-  sampling_data |>
  filter(`Country` == "USA", Gender == "w", LastName %in% usa_womens_roster)


sampling_usa_data_m <-  sampling_data |>
  filter(`Country` == "USA", Gender == "m", LastName %in% usa_mens_roster)


```

```{r simulate func}
simulate_gymnastics_event <- function(event_name, gender, nsimulation) {
  set.seed(123)

  # Select the appropriate dataframe based on gender
  if (gender == "f") {
    gymnast_data <- sampling_usa_data_f
  } else if (gender == "m") {
    gymnast_data <- sampling_usa_data_m
  } else {
    stop("Invalid gender. Use 'f' for female or 'm' for male.")
  }

  # Identify unique gymnasts
  unique_gymnasts <- unique(gymnast_data[, c("FirstName", "LastName")])

  # Create a new dataframe to store sampled scores
  n_iterations_data <- data.frame(
    FirstName = character(),
    LastName = character()
  )

  for (n in 1:nsimulation) {
    sampled_scores_data <- data.frame(
      FirstName = character(),
      LastName = character(),
      stringsAsFactors = FALSE
    )

    for (i in 1:nrow(unique_gymnasts)) {
      # Extract the current gymnast's information
      current_gymnast <- unique_gymnasts[i, ]

      # Subset the data for the current gymnast
      subset_data <- gymnast_data[
        gymnast_data$FirstName == current_gymnast$FirstName &
        gymnast_data$LastName == current_gymnast$LastName &
        gymnast_data$Apparatus == event_name,
      ]

      # Check if the gymnast has at least 5 rows of data
      if (nrow(subset_data) < 5) {
        next  # Skip to the next gymnast
      }

      if (nrow(subset_data) == 0) {
        # If the subset is empty, set the sampled value to 0
        sampled_score <- 0
      } else {
        # Calculate mean and standard deviation
        mean_score <- mean(subset_data$Score)
        sd_score <- sd(subset_data$Score)
        max_cutoff <- max(subset_data$Score) + 0.3

        # Initialize sampled_score
        sampled_score <- NA

        # Sample from the t-distribution until the score is less than or equal to max_cutoff
        while (is.na(sampled_score) || sampled_score > max_cutoff) {
          df <- max(nrow(subset_data) - 1, 1)  # to avoid df being zero
          sampled_score <- mean_score + rt(1, df) * sd_score
        }
      }

      # Create a data frame for the current gymnast's sampled scores
      current_data <- data.frame(
        FirstName = current_gymnast$FirstName,
        LastName = current_gymnast$LastName,
        Score = sampled_score,
        stringsAsFactors = FALSE
      )

      # Append the current data to the overall sampled_scores_data dataframe
      sampled_scores_data <- rbind(sampled_scores_data, current_data)
    }

    # Combine the scores into n_iterations_data
    if (n == 1) {
    n_iterations_data <- sampled_scores_data
    } else {
    n_iterations_data <- cbind(n_iterations_data, sampled_scores_data$Score)
    colnames(n_iterations_data)[ncol(n_iterations_data)] <- paste("Score_", n, sep = "")
  }

  }
    # add an average scores across sims for each athlete
    columns_to_average <- n_iterations_data[, -(1:2)]

    # Calculate the row-wise mean for the selected columns
    n_iterations_data$AverageScore <- rowMeans(columns_to_average, na.rm = TRUE)
    #final_average_df <- n_iterations_data[, c(1, 2, ncol(n_iterations_data))]
    #final_average_df = final_average_df[order(-final_average_df$AverageScore), ]

  return(n_iterations_data)
}
```


```{r womens sims}
# List of women's events
women_events <- c("BB", "UB", "FX", "VT")

# Number of simulations
nsimulation <- 1000

# Loop over women's events
for (event_name in women_events) {
  # Generate dataframe name
  dataframe_name <- paste0(event_name, "_usa_womens_sims")

  # Run the function for the specific event and save the results
  tempsims <- assign(dataframe_name, simulate_gymnastics_event(event_name, "f", nsimulation))
  path <- paste0("App-1/data/07_24_2024_sims/",dataframe_name,".csv")
  write.csv(tempsims, path, row.names = FALSE)
}

```




```{r mens sims}
# List of men's events
men_events <- c("PB", "HB", "PH", "FX", "SR", "VT")

# Number of simulations
nsimulation <- 1000

# Loop over men's events
for (event_name in men_events) {
  # Generate dataframe name
  dataframe_name <- paste0(event_name, "_usa_mens_sims")

  # Run the function for the specific event and save the results
  tempsims <- assign(dataframe_name, simulate_gymnastics_event(event_name, "m", nsimulation))
  path <- paste0("App-1/data/07_24_2024_sims/",dataframe_name,".csv")
  write.csv(tempsims, path, row.names = FALSE)
}

```



### Medaling 



```{r medal-cutoffs function}
## sample 24 times from top 24 athletes mean scores in each apparatus to simulate one "olympics"
## take top 3 scores and those are cutoffs for gold/silver/bronze respectively
# Returns data frame with three rows (gold, silver, bronze) and a column for each simulation
getmedalcutoffs <- function(eventranks, num_simulations = 1000) {
  set.seed(123)
  #distribution <- eventranks$mean_score
  cutoffs <- matrix(NA, nrow = 3, ncol = num_simulations)

  for (i in 1:num_simulations) {
    top_three_scores = numeric(0)
    while (length(unique(top_three_scores))<3){
      # Sample 24 times from the distribution
        mean_score <- mean(eventranks$mean_score)
        sd_score <- sd(eventranks$mean_score)
        max_cutoff <- max(eventranks$mean_score) + 0.3
        # Initialize sampled_score
        sampled_score <- NA
        simulated_scores <- list()
        for (j in 1:24){
          sampled_score <- NA
        # Sample from the t-distribution until the score is less than or equal to max_cutoff
          while (is.na(sampled_score) || sampled_score > max_cutoff) {
            df <- max(nrow(eventranks) - 1, 1)  # to avoid df being zero
            sampled_score <- mean_score + rt(1, df) * sd_score
          }
        #print(sampled_score)
        simulated_scores <- append(simulated_scores,sampled_score)
        }
    # Take the top 3 scores
    simulated_scores = as.numeric(simulated_scores)
    #print(simulated_scores)
    top_three_scores <- head(sort(simulated_scores, decreasing = TRUE), 3)
    }
    # Set the cutoffs for gold, silver, and bronze in the matrix

    cutoffs[, i] <- top_three_scores
  }

  # Convert the matrix to a data frame
  cutoffs_df <- as.data.frame(cutoffs)
  names(cutoffs_df) <- paste0("Simulation_", 1:num_simulations)

  return(cutoffs_df)
}
```

### Event Rankings

```{r rankings}

VT_ranks_f <- cleaned_data |>
  filter(Gender == "w") |>
  group_by(LastName, FirstName, Country, Apparatus) |>
  filter(Apparatus == "VT", n()>=3) |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score)) |>
  arrange(desc(mean_score)) |>
  head(24)

BB_ranks <- cleaned_data |>
  group_by(LastName, FirstName, Country, Apparatus) |>
  filter(Apparatus == "BB", Gender == "w", n()>=3) |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score)) |>
  arrange(desc(mean_score)) |>
  head(24)

UB_ranks <- cleaned_data |>
  group_by(LastName, FirstName, Country, Apparatus) |>
  filter(Apparatus == "UB", Gender == "w", n()>=3) |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score)) |>
  arrange(desc(mean_score)) |>
  head(24)

FX_ranks_f <- cleaned_data |>
  group_by(LastName, FirstName, Country, Apparatus) |>
  filter(Apparatus == "FX", Gender == "w", n()>=3) |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score)) |>
  arrange(desc(mean_score)) |>
  head(24)

#----------------------------------------------------------

VT_ranks_m <- cleaned_data |>
  group_by(LastName, FirstName, Country, Apparatus) |>
  filter(Apparatus == "VT", Gender == "m", n()>=3) |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score)) |>
  arrange(desc(mean_score)) |>
  head(24)

SR_ranks <- cleaned_data |>
  group_by(LastName, FirstName, Country, Apparatus) |>
  filter(Apparatus == "SR", Gender == "m", n()>=3) |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score)) |>
  arrange(desc(mean_score)) |>
  head(24)

PB_ranks <- cleaned_data |>
  group_by(LastName, FirstName, Country, Apparatus) |>
  filter(Apparatus == "PB", Gender == "m", n()>=3) |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score)) |>
  arrange(desc(mean_score)) |>
  head(24)

FX_ranks_m <- cleaned_data |>
  group_by(LastName, FirstName, Country, Apparatus) |>
  filter(Apparatus == "FX", Gender == "m", n()>=3) |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score)) |>
  arrange(desc(mean_score)) |>
  head(24)

PH_ranks <- cleaned_data |>
  group_by(LastName, FirstName, Country, Apparatus) |>
  filter(Apparatus == "PH", Gender == "m", n()>=3) |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score)) |>
  arrange(desc(mean_score)) |>
  head(24)

HB_ranks <- cleaned_data |>
  group_by(LastName, FirstName, Country, Apparatus) |>
  filter(Apparatus == "HB", n()>=3) |>
  summarise(mean_score = mean(Score),
            sd_score = sd(Score)) |>
  arrange(desc(mean_score)) |>
  head(24)

```

```{r get-cutoffs}
BB_medal_cutoffs_w <- getmedalcutoffs(BB_ranks)
FX_medal_cutoffs_w <- getmedalcutoffs(FX_ranks_f)
UB_medal_cutoffs_w <- getmedalcutoffs(UB_ranks)
VT_medal_cutoffs_w <- getmedalcutoffs(VT_ranks_f)

FX_medal_cutoffs_m <- getmedalcutoffs(FX_ranks_m)
SR_medal_cutoffs_m <- getmedalcutoffs(SR_ranks)
HB_medal_cutoffs_m <- getmedalcutoffs(HB_ranks)
PH_medal_cutoffs_m <- getmedalcutoffs(PH_ranks)
VT_medal_cutoffs_m <- getmedalcutoffs(VT_ranks_m)
PB_medal_cutoffs_m <- getmedalcutoffs(PB_ranks)

topAAmen <- cleaned_data %>% 
  filter(Gender == "m", Round == "AAfinal") %>% 
  group_by(LastName, FirstName, Competition, Country) %>% 
  filter(n()<7) %>% 
  summarize(AAtotal = sum(Score))

topAAwomen <- cleaned_data %>% 
  filter(Gender == "w", Round == "AAfinal") %>% 
  group_by(LastName, FirstName, Competition, Country) %>% 
  filter(n()<5) %>% 
  summarize(AAtotal = sum(Score))

top24AAmen <- topAAmen %>% 
  group_by(LastName,FirstName,Country) %>% 
  summarize(mean_score = mean(AAtotal)) %>% 
  arrange(desc(mean_score)) %>% 
  head(24)

top24AAwomen <- topAAwomen %>% 
  group_by(LastName,FirstName,Country) %>% 
  summarize(mean_score = mean(AAtotal)) %>% 
  arrange(desc(mean_score)) %>% 
  head(24)

allroundmen_cutoffs <-getmedalcutoffs(top24AAmen)
allroudwomen_cutoffs <- getmedalcutoffs(top24AAwomen)
```

```{r get-model-probs-func}
calculatePodiumPercentages <- function(df, thresholds) {
  # Number of gymnasts
  num_gymnasts <- nrow(df)
  
  # Initialize an empty dataframe for the results
  results <- data.frame(
    firstName = df[, 1],
    lastName = df[, 2],
    bronze_percentage = numeric(num_gymnasts),
    silver_percentage = numeric(num_gymnasts),
    gold_percentage = numeric(num_gymnasts),
    stringsAsFactors = FALSE
  )
  
  # Iterating over each set of scores
  for (i in 1:1000) {
    # Extract the scores for the ith sample and the thresholds
    sample_scores <- df[, i + 2]
    gold_threshold <- thresholds[1, i]
    silver_threshold <- thresholds[2, i]
    bronze_threshold <- thresholds[3, i]

    # Count placements based on thresholds
    results$gold_percentage <- results$gold_percentage + (sample_scores >= gold_threshold)
    results$silver_percentage <- results$silver_percentage + (sample_scores >= silver_threshold & sample_scores < gold_threshold)
    results$bronze_percentage <- results$bronze_percentage + (sample_scores >= bronze_threshold & sample_scores < silver_threshold)
  }

  # Convert counts to percentages
  results$gold_percentage <- (results$gold_percentage / 1000)
  results$silver_percentage <- (results$silver_percentage / 1000)
  results$bronze_percentage <- (results$bronze_percentage / 1000)

  # Sort the dataframe by gold_percentage in descending order
  results <- results[order(-results$gold_percentage), ]
  
  return(results)
}
```

```{r write-percs-example}
sims_data <- read_csv("App-1/data/07_24_2024_sims/AA_usa_mens_sims.csv")
percs <- calculatePodiumPercentages(sims_data, allroundmen_cutoffs)
write.csv(percs, 'App-1/data/07_24_2024_sims/m_AA.csv', row.names=FALSE)
```

```{r medal-counts-f}
f_FX <- read_csv("App-1/data/07_24_2024_sims/w_FX_medalpercentages.csv")
f_BB <- read_csv("App-1/data/07_24_2024_sims/w_BB_medalpercentages.csv")
f_VT <- read_csv("App-1/data/07_24_2024_sims/w_VT_medalpercentages.csv")
f_UB <- read_csv("App-1/data/07_24_2024_sims/w_UB_medalpercentages.csv")

# Function to normalize and rename percentage columns
normalize_and_rename <- function(df, suffix) {
  df |>
    mutate(across(contains("percentage"), ~ . / 1)) |>
    rename_with(~ paste0(., "_", suffix), contains("percentage"))
}

# Apply the function to each dataframe with a unique suffix
f_BB <- normalize_and_rename(f_BB, "BB")
f_FX <- normalize_and_rename(f_FX, "FX")
f_UB <- normalize_and_rename(f_UB, "UB")
f_VT <- normalize_and_rename(f_VT, "VT")

# Combine the dataframes using full join
combined_df <- reduce(list(f_BB, f_FX, f_UB, f_VT), full_join, by = c("FirstName", "LastName"))

# Replace NA with 0
combined_df[is.na(combined_df)] <- 0

#write.csv(combined_df, 'App-1/data/07_24_2024_sims/f.csv', row.names=FALSE)
```

```{r medal-counts-m}
m_FX <- read_csv("App-1/data/07_24_2024_sims/m_FX_medalpercentages.csv")
m_SR <- read_csv("App-1/data/07_24_2024_sims/m_SR_medalpercentages.csv")
m_VT <- read_csv("App-1/data/07_24_2024_sims/m_VT_medalpercentages.csv")
m_PB <- read_csv("App-1/data/07_24_2024_sims/m_PB_medalpercentages.csv")
m_PH <- read_csv("App-1/data/07_24_2024_sims/m_PH_medalpercentages.csv")
m_HB <- read_csv("App-1/data/07_24_2024_sims/m_HB_medalpercentages.csv")

# Function to normalize and rename percentage columns
normalize_and_rename <- function(df, suffix) {
  df |>
    mutate(across(contains("percentage"), ~ . / 1)) |>
    rename_with(~ paste0(., "_", suffix), contains("percentage"))
}

# Apply the function to each dataframe with a unique suffix
m_SR <- normalize_and_rename(m_SR, "SR")
m_FX <- normalize_and_rename(m_FX, "FX")
m_PB <- normalize_and_rename(m_PB, "PB")
m_VT <- normalize_and_rename(m_VT, "VT")
m_PH <- normalize_and_rename(m_PH, "PH")
m_HB <- normalize_and_rename(m_HB, "HB")

# Combine the dataframes using full join
combined_df <- reduce(list(m_SR, m_FX, m_PB, m_VT, m_PH, m_HB), full_join, by = c("FirstName", "LastName"))

# Replace NA with 0
combined_df[is.na(combined_df)] <- 0

#write.csv(combined_df, 'App-1/data/07_24_2024_sims/m.csv', row.names=FALSE)
```

```{r all-around-sims womens}
BB_sims <- read_csv("App-1/data/07_24_2024_sims/BB_usa_womens_sims.csv")
FX_sims <- read_csv("App-1/data/07_24_2024_sims/FX_usa_womens_sims.csv")
UB_sims <- read_csv("App-1/data/07_24_2024_sims/UB_usa_womens_sims.csv")
VT_sims <- read_csv("App-1/data/07_24_2024_sims/VT_usa_womens_sims.csv")

# Define a function to replace NA with 0 and drop the average score column
prepare_df <- function(df) {
  df %>% 
    mutate(across(starts_with("Score"), ~ replace_na(., 0)))
}

BB_sims_prepared <- prepare_df(BB_sims)
FX_sims_prepared <- prepare_df(FX_sims)
UB_sims_prepared <- prepare_df(UB_sims)
VT_sims_prepared <- prepare_df(VT_sims)

# Use left joins to combine the dataframes
combined_AA_df <- BB_sims_prepared %>%
  left_join(FX_sims_prepared, by = c("FirstName", "LastName")) %>%
  left_join(UB_sims_prepared, by = c("FirstName", "LastName")) %>%
  left_join(VT_sims_prepared, by = c("FirstName", "LastName"))
```



```{r sum-across-events-women}
# Assuming your dataframe is called 'your_dataframe'
# Assuming you have 4004 columns and 38 rows

# Create a vector of column indices to sum
original_data <- combined_AA_df[, -(1:2)]
names <- combined_AA_df[, (1:2)]


# Sum every 1000th column and store the result in the condensed dataframe
condensed_data <- data.frame(matrix(NA, nrow = nrow(names), ncol = 1000))

# Loop through each group of 1000 columns
for (i in 1:1001) {
  # Identify the columns in the current group
  current_group_columns <- c(i, i + 1000,i+2000,i+3000)
  #print(current_group_columns)
  # Sum the values across the columns in the current group
  condensed_data[, i] <- rowSums(original_data[, current_group_columns], na.rm = TRUE)
}

# Rename the columns of the condensed dataframe
colnames(condensed_data) <- paste0("Condensed_Column_", 1:ncol(condensed_data))

# Print or use the condensed dataframe as needed
combinedfinalAA <- cbind(names,condensed_data)

write.csv(combinedfinalAA, "App-1/data/07_24_2024_sims/AA_usa_womens_sims.csv", row.names = FALSE)
```


```{r all-around-sims men}
HB_sims_m <- read_csv("App-1/data/07_24_2024_sims/HB_usa_mens_sims.csv")
FX_sims_m <- read_csv("App-1/data/07_24_2024_sims/FX_usa_mens_sims.csv")
PB_sims_m <- read_csv("App-1/data/07_24_2024_sims/PB_usa_mens_sims.csv")
VT_sims_m <- read_csv("App-1/data/07_24_2024_sims/VT_usa_mens_sims.csv")
PH_sims_m <- read_csv("App-1/data/07_24_2024_sims/PH_usa_mens_sims.csv")
SR_sims_m <- read_csv("App-1/data/07_24_2024_sims/SR_usa_mens_sims.csv")

# Define a function to replace NA with 0 and drop the average score column
prepare_df <- function(df) {
  df %>% 
    mutate(across(starts_with("Score"), ~ replace_na(., 0)))
}

HB_sims_prepared_m <- prepare_df(HB_sims_m)
FX_sims_prepared_m <- prepare_df(FX_sims_m)
PB_sims_prepared_m <- prepare_df(PB_sims_m)
VT_sims_prepared_m <- prepare_df(VT_sims_m)
PH_sims_prepared_m <- prepare_df(PH_sims_m)
SR_sims_prepared_m <- prepare_df(SR_sims_m)

# Use left joins to combine the dataframes
combined_AA_df_m <- HB_sims_prepared_m %>%
  left_join(FX_sims_prepared_m, by = c("FirstName", "LastName")) %>%
  left_join(PB_sims_prepared_m, by = c("FirstName", "LastName")) %>%
  left_join(VT_sims_prepared_m, by = c("FirstName", "LastName")) %>% 
  left_join(PH_sims_prepared_m, by = c("FirstName", "LastName")) %>% 
  left_join(SR_sims_prepared_m, by = c("FirstName", "LastName")) 
```

```{r sum-across-events-men}
# Create a vector of column indices to sum
original_data <- combined_AA_df_m[, -(1:2)]
names <- combined_AA_df_m[, (1:2)]


# Sum every 1000th column and store the result in the condensed dataframe
condensed_data <- data.frame(matrix(NA, nrow = nrow(original_data), ncol = 1000))

# Loop through each group of 1000 columns
for (i in 1:1001) {
  # Identify the columns in the current group
  current_group_columns <- c(i + 1000,i+2000,i+3000,i+4000,i+5000)
  #print(current_group_columns)
  # Sum the values across the columns in the current group
  condensed_data[, i] <- rowSums(original_data[, current_group_columns], na.rm = TRUE)
}

# Rename the columns of the condensed dataframe
colnames(condensed_data) <- paste0("Condensed_Column_", 1:ncol(condensed_data))

# Print or use the condensed dataframe as needed
combinedfinalAA_m <- cbind(names,condensed_data)

#write.csv(combinedfinalAA_m, "App-1/data/07_24_2024_sims/AA_usa_mens_sims.csv", row.names = FALSE)
```

```{r load-data}
women <- read_csv("App-1/data/07_24_2024_sims/f.csv")
men <- read_csv("App-1/data/07_24_2024_sims/m.csv")
w_AA <- read_csv("App-1/data/07_24_2024_sims/w_AA.csv")
m_AA <- read_csv("App-1/data/07_24_2024_sims/m_AA.csv")
```

```{r sean-df-womens}
FX_usa_womens_sims <- read_csv("App-1/data/07_24_2024_sims/FX_usa_womens_sims.csv")
AA_usa_womens_sims <- read_csv("App-1/data/07_24_2024_sims/AA_usa_womens_sims.csv")
BB_usa_womens_sims <- read_csv("App-1/data/07_24_2024_sims/BB_usa_womens_sims.csv")
UB_usa_womens_sims <- read_csv("App-1/data/07_24_2024_sims/UB_usa_womens_sims.csv")
VT_usa_womens_sims <- read_csv("App-1/data/07_24_2024_sims/VT_usa_womens_sims.csv")

#AA_usa_womens_sims <- AA_usa_womens_sims[, 2:1003]

colnames(AA_usa_womens_sims)[ncol(AA_usa_womens_sims)] <- "AverageScore"

# Assuming the datasets are already loaded into the environment
datasets <- list(AA = AA_usa_womens_sims, BB = BB_usa_womens_sims, VT = VT_usa_womens_sims, UB = UB_usa_womens_sims, FX = FX_usa_womens_sims)

# Function to process each dataset
process_dataset <- function(df, event_name) {
  # Create FullName column by concatenating FirstName and capitalized LastName
  df$FullName <- paste(df$FirstName, sapply(strsplit(tolower(df$LastName), " "), function(x) {
    # Capitalize each part of a possibly hyphenated or spaced last name
    paste(sapply(x, function(y) {
      paste0(toupper(substring(y, 1, 1)), substring(y, 2))
    }), collapse = " ")
  }), sep=" ")

  # Select only FullName and AverageScore columns
  df <- df[, c("FullName", "AverageScore")]
  
  # Add the Event column
  df$Event <- event_name
  
  return(df)
}

# Apply the function to each dataset
processed_datasets <- lapply(names(datasets), function(name) {
  process_dataset(datasets[[name]], name)
})

# Combine all processed datasets into one
usa_womens_avs <- do.call(rbind, processed_datasets)



f <- read_csv("App-1/data/07_24_2024_sims/f.csv")
w_AA <- read_csv("App-1/data/07_24_2024_sims/w_AA.csv")

# Correcting the case of the LastName in the f dataset
f$LastName <- sapply(strsplit(tolower(f$LastName), " "), function(x) {
  paste(sapply(x, function(y) {
    paste0(toupper(substring(y, 1, 1)), substring(y, 2))
  }), collapse = " ")
})

# Create FullName in f dataset
#f$FullName <- paste(f$FirstName, f$LastName, sep=" ")

#w_AA$lastName <- sapply(strsplit(tolower(w_AA$lastName), " "), function(x) {
#  paste(sapply(x, function(y) {
#    paste0(toupper(substring(y, 1, 1)), substring(y, 2))
#  }), collapse = " ")
#})

# Create FullName in f dataset
#w_AA$FullName <- paste(w_AA$firstName, w_AA$lastName, sep=" ")

# Renaming the percentage columns in w_AA to match the format in f
#colnames(w_AA)[colnames(w_AA) %in% c("bronze_percentage", "silver_percentage", "gold_percentage")] <- 
#  c("bronze_percentage_AA", "silver_percentage_AA", "gold_percentage_AA")

# Joining w_AA with f to add the AA percentages
#f <- merge(f, w_AA[, c("FullName", "bronze_percentage_AA", "silver_percentage_AA", "gold_percentage_AA")], 
#           by = "FullName", all.x = TRUE)

# Define a function to extract percentages based on the event and percentage type
get_event_percentage <- function(full_name, event, percentage_type) {
  f_row <- f[f$FullName == full_name, ]
  if (nrow(f_row) == 0) {
    return(NA)
  } else {
    col_name <- paste(percentage_type, "_percentage_", event, sep = "")
    return(f_row[[col_name]])
  }
}

# Adding the GoldPercentage, SilverPercentage, and BronzePercentage columns to usa_womens_avs
usa_womens_avs$GoldPercentage <- mapply(get_event_percentage, usa_womens_avs$FullName, usa_womens_avs$Event, MoreArgs = list(percentage_type = "gold"))
usa_womens_avs$SilverPercentage <- mapply(get_event_percentage, usa_womens_avs$FullName, usa_womens_avs$Event, MoreArgs = list(percentage_type = "silver"))
usa_womens_avs$BronzePercentage <- mapply(get_event_percentage, usa_womens_avs$FullName, usa_womens_avs$Event, MoreArgs = list(percentage_type = "bronze"))

write.csv(usa_womens_avs, "App-1/data/07_24_2024_sims/usa_womens_avs.csv", row.names = FALSE)
```

```{r sean-df-mens}
PB_usa_mens_sims <- read_csv("App-1/data/07_24_2024_sims/PB_usa_mens_sims.csv")
AA_usa_mens_sims <- read_csv("App-1/data/07_24_2024_sims/AA_usa_mens_sims.csv")
PH_usa_mens_sims <- read_csv("App-1/data/07_24_2024_sims/PH_usa_mens_sims.csv")
SR_usa_mens_sims <- read_csv("App-1/data/07_24_2024_sims/SR_usa_mens_sims.csv")
VT_usa_mens_sims <- read_csv("App-1/data/07_24_2024_sims/VT_usa_mens_sims.csv")
HB_usa_mens_sims <- read_csv("App-1/data/07_24_2024_sims/HB_usa_mens_sims.csv")
FX_usa_mens_sims <- read_csv("App-1/data/07_24_2024_sims/FX_usa_mens_sims.csv")

AA_usa_mens_sims <- AA_usa_mens_sims[, 2:1004]

colnames(AA_usa_mens_sims)[ncol(AA_usa_mens_sims)] <- "AverageScore"

# Assuming the datasets are already loaded into the environment
datasets_m <- list(AA = AA_usa_mens_sims, PB = PB_usa_mens_sims, VT = VT_usa_mens_sims, PH = PH_usa_mens_sims, SR = SR_usa_mens_sims, HB = HB_usa_mens_sims, FX = FX_usa_mens_sims)

# Function to process each dataset
process_dataset <- function(df, event_name) {
  # Create FullName column by concatenating FirstName and capitalized LastName
  df$FullName <- paste(df$FirstName, sapply(strsplit(tolower(df$LastName), " "), function(x) {
    # Capitalize each part of a possibly hyphenated or spaced last name
    paste(sapply(x, function(y) {
      paste0(toupper(substring(y, 1, 1)), substring(y, 2))
    }), collapse = " ")
  }), sep=" ")

  # Select only FullName and AverageScore columns
  df <- df[, c("FullName", "AverageScore")]
  
  # Add the Event column
  df$Event <- event_name
  
  return(df)
}

# Apply the function to each dataset
processed_datasets_m <- lapply(names(datasets_m), function(name) {
  process_dataset(datasets_m[[name]], name)
})

# Combine all processed datasets into one
usa_mens_avs <- do.call(rbind, processed_datasets_m)


m <- read_csv("App-1/data/expected_medals/m.csv")
m_AA <- read_csv("App-1/data/event_percentages/m_AA.csv")

# Correcting the case of the LastName in the f dataset
m$LastName <- sapply(strsplit(tolower(m$LastName), " "), function(x) {
  paste(sapply(x, function(y) {
    paste0(toupper(substring(y, 1, 1)), substring(y, 2))
  }), collapse = " ")
})

# Create FullName in f dataset
m$FullName <- paste(m$FirstName, m$LastName, sep=" ")

m_AA$lastName <- sapply(strsplit(tolower(m_AA$lastName), " "), function(x) {
  paste(sapply(x, function(y) {
    paste0(toupper(substring(y, 1, 1)), substring(y, 2))
  }), collapse = " ")
})

# Create FullName in f dataset
m_AA$FullName <- paste(m_AA$firstName, m_AA$lastName, sep=" ")

# Renaming the percentage columns in w_AA to match the format in f
colnames(m_AA)[colnames(m_AA) %in% c("bronze_percentage", "silver_percentage", "gold_percentage")] <- 
  c("bronze_percentage_AA", "silver_percentage_AA", "gold_percentage_AA")

# Joining w_AA with f to add the AA percentages
m <- merge(m, m_AA[, c("FullName", "bronze_percentage_AA", "silver_percentage_AA", "gold_percentage_AA")], 
           by = "FullName", all.x = TRUE)

# Define a function to extract percentages based on the event and percentage type
get_event_percentage <- function(full_name, event, percentage_type) {
  m_row <- m[m$FullName == full_name, ]
  if (nrow(m_row) == 0) {
    return(NA)
  } else {
    col_name <- paste(percentage_type, "_percentage_", event, sep = "")
    return(m_row[[col_name]])
  }
}

# Adding the GoldPercentage, SilverPercentage, and BronzePercentage columns to usa_mens_avs
usa_mens_avs$GoldPercentage <- mapply(get_event_percentage, usa_mens_avs$FullName, usa_mens_avs$Event, MoreArgs = list(percentage_type = "gold"))
usa_mens_avs$SilverPercentage <- mapply(get_event_percentage, usa_mens_avs$FullName, usa_mens_avs$Event, MoreArgs = list(percentage_type = "silver"))
usa_mens_avs$BronzePercentage <- mapply(get_event_percentage, usa_mens_avs$FullName, usa_mens_avs$Event, MoreArgs = list(percentage_type = "bronze"))

write.csv(usa_mens_avs, "App-1/data/07_24_2024_sims/usa_mens_avs.csv")
```

